/* =========================================================
   CHAT: Samira Vance
   ========================================================= */

window.CHATS_DATA.samira = {
  name: "Samira Vance",
  bio: "the blue mug has heard everything",
  avatarInitials: "S",
  avatarColor: "#3F6C71",
  preview: "are u safe?",
  time: "11:42 PM",
  unreadCount: 6,
  messages: [
    { day: "Saturday 22 November" },
    { from: "samira", time: "3:15 PM", text: "u forgot your yellow scarf again" },
    { from: "samira", time: "3:15 PM", text: "i hung it in the staff room" },
    { from: "samira", time: "3:15 PM", text: "it's been there since yesterday" },
    { from: "samira", time: "3:16 PM", text: "it's starting to look like a decoration" },
    { from: "maya", time: "3:18 PM", text: "keep it there. the library is freezing anyway" },
    { from: "samira", time: "3:18 PM", text: "the library is always freezing" },
    { from: "samira", time: "3:18 PM", text: "that's why you wear a coat" },
    { from: "maya", time: "3:19 PM", text: "i have a coat" },
    { from: "samira", time: "3:19 PM", text: "you have a cardigan" },
    { from: "samira", time: "3:19 PM", text: "that's not a coat" },
    { from: "maya", time: "3:20 PM", text: "it's warm" },
    { from: "samira", time: "3:20 PM", text: "it's not" },
    { from: "samira", time: "3:20 PM", text: "anyway" },
    { from: "samira", time: "3:21 PM", text: "are you coming by later?" },
    { from: "samira", time: "3:21 PM", text: "i'm on shift till 6" },
    { from: "maya", time: "3:22 PM", text: "maybe" },
    { from: "maya", time: "3:22 PM", text: "i have to finish something first" },
    { from: "samira", time: "3:22 PM", text: "finish what" },
    { from: "samira", time: "3:22 PM", text: "you're always finishing something" },
    { from: "maya", time: "3:23 PM", text: "just something" },
    { from: "samira", time: "3:23 PM", text: "mysterious" },
    { from: "samira", time: "3:23 PM", text: "i hate when you do that" },
    { from: "maya", time: "3:24 PM", text: "i know" },
    { from: "samira", time: "3:24 PM", text: "you're lucky i love you" },

    { day: "Saturday 22 November, later" },
    { from: "samira", time: "4:05 PM", text: "ok so" },
    { from: "samira", time: "4:05 PM", text: "update on the kyle situation" },
    { from: "samira", time: "4:05 PM", text: "he's still pretending nothing happened" },
    { from: "samira", time: "4:06 PM", text: "he walked past me today and i swear he flinched" },
    { from: "maya", time: "4:07 PM", text: "probably because you keep staring at him" },
    { from: "samira", time: "4:07 PM", text: "i'm not staring" },
    { from: "samira", time: "4:07 PM", text: "i'm observing" },
    { from: "samira", time: "4:07 PM", text: "there's a difference" },
    { from: "maya", time: "4:08 PM", text: "there really isn't" },
    { from: "samira", time: "4:08 PM", text: "you're so mean to me" },
    { from: "maya", time: "4:09 PM", text: "i'm honest" },
    { from: "samira", time: "4:09 PM", text: "same thing" },
    { from: "samira", time: "4:10 PM", text: "anyway" },
    { from: "samira", time: "4:10 PM", text: "are you okay?" },
    { from: "samira", time: "4:10 PM", text: "you seem off" },
    { from: "maya", time: "4:11 PM", text: "i'm fine" },
    { from: "samira", time: "4:11 PM", text: "you're not" },
    { from: "samira", time: "4:11 PM", text: "i can tell" },
    { from: "maya", time: "4:12 PM", text: "how can you tell" },
    { from: "samira", time: "4:12 PM", text: "because you've sent me three messages today" },
    { from: "samira", time: "4:12 PM", text: "that's like a record" },
    { from: "samira", time: "4:13 PM", text: "usually you send one word replies and disappear" },
    { from: "maya", time: "4:14 PM", text: "i've been busy" },
    { from: "samira", time: "4:14 PM", text: "with what" },
    { from: "maya", time: "4:15 PM", text: "stuff" },
    { from: "samira", time: "4:15 PM", text: "MAYA" },
    { from: "maya", time: "4:16 PM", text: "i'll tell you later" },
    { from: "maya", time: "4:16 PM", text: "i promise" },
    { from: "samira", time: "4:16 PM", text: "you better" },
    { from: "samira", time: "4:16 PM", text: "i'm holding you to that" },
    { from: "samira", time: "4:17 PM", text: "literally" },
    { from: "samira", time: "4:17 PM", text: "i have a mental list" },
    { from: "maya", time: "4:18 PM", text: "you don't have a mental list" },
    { from: "samira", time: "4:18 PM", text: "i do" },
    { from: "samira", time: "4:18 PM", text: "item one: maya owes me an explanation" },
    { from: "samira", time: "4:18 PM", text: "item two: maya needs to stop being weird" },
    { from: "samira", time: "4:19 PM", text: "item three: maya needs to eat something" },
    { from: "maya", time: "4:20 PM", text: "i ate" },
    { from: "samira", time: "4:20 PM", text: "what did you eat" },
    { from: "maya", time: "4:20 PM", text: "food" },
    { from: "samira", time: "4:21 PM", text: "what food" },
    { from: "maya", time: "4:21 PM", text: "does it matter" },
    { from: "samira", time: "4:21 PM", text: "yes" },
    { from: "samira", time: "4:21 PM", text: "because i know you" },
    { from: "samira", time: "4:22 PM", text: "you probably had a granola bar and called it a meal" },
    { from: "maya", time: "4:22 PM", text: "it was two granola bars" },
    { from: "samira", time: "4:22 PM", text: "MAYAAAA" },

    { day: "Sunday 23 November" },
    { from: "samira", time: "10:23 AM", text: "did you see the email from sterling" },
    { from: "samira", time: "10:23 AM", text: "about the mock results" },
    { from: "maya", time: "10:24 AM", text: "yeah" },
    { from: "samira", time: "10:24 AM", text: "you got top marks again" },
    { from: "samira", time: "10:24 AM", text: "obviously" },
    { from: "maya", time: "10:25 AM", text: "obviously" },
    { from: "samira", time: "10:25 AM", text: "don't be smug" },
    { from: "samira", time: "10:25 AM", text: "it's not a good look" },
    { from: "maya", time: "10:25 AM", text: "it's not smug" },
    { from: "maya", time: "10:25 AM", text: "it's accurate" },
    { from: "samira", time: "10:26 AM", text: "you're impossible" },
    { from: "samira", time: "10:26 AM", text: "anyway" },
    { from: "samira", time: "10:26 AM", text: "julian got second" },
    { from: "samira", time: "10:26 AM", text: "he's been sulking all morning" },
    { from: "maya", time: "10:27 AM", text: "he always sulks" },
    { from: "samira", time: "10:27 AM", text: "yeah but this time it's worse" },
    { from: "samira", time: "10:27 AM", text: "he literally didn't talk to anyone at lunch" },
    { from: "samira", time: "10:27 AM", text: "just sat there staring at his phone" },
    { from: "maya", time: "10:28 AM", text: "maybe he's just having a bad day" },
    { from: "samira", time: "10:28 AM", text: "maybe" },
    { from: "samira", time: "10:28 AM", text: "or maybe he's plotting your downfall" },
    { from: "maya", time: "10:29 AM", text: "he can try" },
    { from: "samira", time: "10:29 AM", text: "maya" },
    { from: "samira", time: "10:29 AM", text: "that's not funny" },
    { from: "maya", time: "10:29 AM", text: "i wasn't joking" },
    { from: "samira", time: "10:30 AM", text: "i know" },

    { day: "Sunday 23 November, later" },
    { from: "samira", time: "2:47 PM", text: "i'm bored" },
    { from: "samira", time: "2:47 PM", text: "entertain me" },
    { from: "maya", time: "2:48 PM", text: "i'm in the library" },
    { from: "samira", time: "2:48 PM", text: "so" },
    { from: "maya", time: "2:49 PM", text: "so i'm busy" },
    { from: "samira", time: "2:49 PM", text: "doing what" },
    { from: "maya", time: "2:49 PM", text: "reading" },
    { from: "samira", time: "2:50 PM", text: "reading what" },
    { from: "maya", time: "2:50 PM", text: "a book" },
    { from: "samira", time: "2:50 PM", text: "what book" },
    { from: "maya", time: "2:51 PM", text: "you wouldn't be interested" },
    { from: "samira", time: "2:51 PM", text: "try me" },
    { from: "maya", time: "2:52 PM", text: "it's about cryptography" },
    { from: "samira", time: "2:52 PM", text: "i regret asking" },
    { from: "samira", time: "2:52 PM", text: "why cryptography" },
    { from: "maya", time: "2:53 PM", text: "because it's interesting" },
    { from: "samira", time: "2:53 PM", text: "you're such a nerd" },
    { from: "maya", time: "2:53 PM", text: "you say that like it's an insult" },
    { from: "samira", time: "2:54 PM", text: "it's not" },
    { from: "samira", time: "2:54 PM", text: "it's an observation" },
    { from: "samira", time: "2:54 PM", text: "i'm observing" },
    { from: "maya", time: "2:55 PM", text: "that's my line" },
    { from: "samira", time: "2:55 PM", text: "i'm borrowing it" },
    { from: "samira", time: "2:55 PM", text: "anyway" },
    { from: "samira", time: "2:55 PM", text: "are you coming to the kettle later" },
    { from: "maya", time: "2:56 PM", text: "maybe" },
    { from: "samira", time: "2:56 PM", text: "you always say maybe" },
    { from: "maya", time: "2:56 PM", text: "because i'm not sure" },
    { from: "samira", time: "2:57 PM", text: "just say yes" },
    { from: "maya", time: "2:57 PM", text: "yes" },
    { from: "samira", time: "2:57 PM", text: "see how easy that was" },
    { from: "maya", time: "2:58 PM", text: "you're very demanding" },
    { from: "samira", time: "2:58 PM", text: "i'm very charming" },
    { from: "maya", time: "2:58 PM", text: "sure" },
    { from: "samira", time: "2:59 PM", text: "i am" },
    { from: "samira", time: "2:59 PM", text: "everyone thinks so" },
    { from: "maya", time: "2:59 PM", text: "who is everyone" },
    { from: "samira", time: "3:00 PM", text: "the customers" },
    { from: "maya", time: "3:00 PM", text: "the customers who come for coffee" },
    { from: "samira", time: "3:00 PM", text: "yes" },
    { from: "maya", time: "3:01 PM", text: "they're not here for you" },
    { from: "samira", time: "3:01 PM", text: "they might be" },
    { from: "maya", time: "3:01 PM", text: "they're not" },

    { day: "Monday 24 November" },
    { from: "samira", time: "9:12 AM", text: "MAYA" },
    { from: "samira", time: "9:12 AM", text: "MAYA WAKE UP" },
    { from: "samira", time: "9:12 AM", text: "i found something" },
    { from: "maya", time: "9:14 AM", text: "what" },
    { from: "samira", time: "9:14 AM", text: "you know the weird guy who comes in every morning" },
    { from: "samira", time: "9:14 AM", text: "the one with the grey coat" },
    { from: "maya", time: "9:15 AM", text: "the one who stares" },
    { from: "samira", time: "9:15 AM", text: "yes" },
    { from: "samira", time: "9:15 AM", text: "he came in again today" },
    { from: "samira", time: "9:15 AM", text: "and he was asking about you" },
    { from: "maya", time: "9:16 AM", text: "what" },
    { from: "samira", time: "9:16 AM", text: "he asked if you were working today" },
    { from: "samira", time: "9:16 AM", text: "i said no" },
    { from: "samira", time: "9:16 AM", text: "he just nodded and left" },
    { from: "samira", time: "9:17 AM", text: "it was weird" },
    { from: "maya", time: "9:17 AM", text: "what did he look like" },
    { from: "samira", time: "9:17 AM", text: "older" },
    { from: "samira", time: "9:17 AM", text: "grey coat" },
    { from: "samira", time: "9:17 AM", text: "grey hair" },
    { from: "samira", time: "9:18 AM", text: "didn't order anything" },
    { from: "samira", time: "9:18 AM", text: "just stood there for a bit and left" },
    { from: "maya", time: "9:19 AM", text: "did he say anything else" },
    { from: "samira", time: "9:19 AM", text: "no" },
    { from: "samira", time: "9:19 AM", text: "just that" },
    { from: "samira", time: "9:19 AM", text: "maya are you okay" },
    { from: "samira", time: "9:20 AM", text: "you're typing and then stopping" },
    { from: "samira", time: "9:20 AM", text: "i can see the dots" },
    { from: "maya", time: "9:21 AM", text: "i'm fine" },
    { from: "maya", time: "9:21 AM", text: "just thinking" },
    { from: "samira", time: "9:21 AM", text: "about what" },
    { from: "maya", time: "9:21 AM", text: "nothing" },
    { from: "samira", time: "9:22 AM", text: "MAYA" },
    { from: "maya", time: "9:22 AM", text: "i'll call you later" },
    { from: "samira", time: "9:22 AM", text: "you better" },
    { from: "samira", time: "9:22 AM", text: "i'm worried" },
    { from: "maya", time: "9:23 AM", text: "don't be" },
    { from: "samira", time: "9:23 AM", text: "too late" },

    { day: "Monday 24 November, evening" },
    { from: "samira", time: "6:38 PM", text: "did you call" },
    { from: "samira", time: "6:38 PM", text: "you said you'd call" },
    { from: "samira", time: "6:38 PM", text: "maya" },
    { from: "samira", time: "6:39 PM", text: "i'm waiting" },
    { from: "samira", time: "6:45 PM", text: "fine" },
    { from: "samira", time: "6:45 PM", text: "ignore me" },
    { from: "samira", time: "6:45 PM", text: "see if i care" },
    { from: "samira", time: "6:46 PM", text: "(i care)" },
    { from: "samira", time: "6:46 PM", text: "(i care a lot)" },
    { from: "samira", time: "6:46 PM", text: "(please text me back)" },

    { day: "Tuesday 25 November" },
    { from: "samira", time: "8:15 AM", text: "maya" },
    { from: "samira", time: "8:15 AM", text: "maya" },
    { from: "samira", time: "8:15 AM", text: "MAYA" },
    { from: "samira", time: "8:15 AM", text: "you're scaring me" },
    { from: "samira", time: "8:16 AM", text: "you haven't replied in like 12 hours" },
    { from: "samira", time: "8:16 AM", text: "which is normal for you" },
    { from: "samira", time: "8:16 AM", text: "but this feels different" },
    { from: "samira", time: "8:16 AM", text: "please just tell me you're okay" },
    { from: "maya", time: "8:20 AM", text: "i'm okay" },
    { from: "samira", time: "8:20 AM", text: "oh thank god" },
    { from: "samira", time: "8:20 AM", text: "where were you" },
    { from: "maya", time: "8:21 AM", text: "busy" },
    { from: "samira", time: "8:21 AM", text: "doing what" },
    { from: "maya", time: "8:21 AM", text: "something" },
    { from: "samira", time: "8:22 AM", text: "maya" },
    { from: "samira", time: "8:22 AM", text: "you're being weird again" },
    { from: "maya", time: "8:23 AM", text: "i'm sorry" },
    { from: "maya", time: "8:23 AM", text: "i'll explain later" },
    { from: "maya", time: "8:23 AM", text: "i promise" },
    { from: "samira", time: "8:24 AM", text: "you keep saying that" },
    { from: "maya", time: "8:24 AM", text: "i know" },
    { from: "samira", time: "8:24 AM", text: "fine" },
    { from: "samira", time: "8:24 AM", text: "but you owe me" },
    { from: "samira", time: "8:25 AM", text: "big time" },
    { from: "samira", time: "8:25 AM", text: "like, i'm talking about a full explanation" },
    { from: "samira", time: "8:25 AM", text: "with details" },
    { from: "samira", time: "8:25 AM", text: "and maybe cake" },
    { from: "maya", time: "8:26 AM", text: "deal" },
    { from: "samira", time: "8:26 AM", text: "okay" },
    { from: "samira", time: "8:26 AM", text: "i love you" },
    { from: "samira", time: "8:26 AM", text: "even when you're weird" },
    { from: "maya", time: "8:27 AM", text: "i love you too" },
    { from: "samira", time: "8:27 AM", text: "don't get sappy on me" },
    { from: "maya", time: "8:27 AM", text: "you started it" },
    { from: "samira", time: "8:28 AM", text: "i know" },

    { day: "Tuesday 25 November, afternoon" },
    { from: "samira", time: "2:30 PM", text: "ok so" },
    { from: "samira", time: "2:30 PM", text: "weird guy came back" },
    { from: "samira", time: "2:30 PM", text: "the grey coat guy" },
    { from: "samira", time: "2:31 PM", text: "he asked for you again" },
    { from: "samira", time: "2:31 PM", text: "i told him you weren't here" },
    { from: "samira", time: "2:31 PM", text: "he just nodded and left" },
    { from: "samira", time: "2:32 PM", text: "but he looked at the staff room door" },
    { from: "samira", time: "2:32 PM", text: "like he was looking for something" },
    { from: "maya", time: "2:33 PM", text: "did he say anything" },
    { from: "samira", time: "2:33 PM", text: "no" },
    { from: "samira", time: "2:33 PM", text: "but maya" },
    { from: "samira", time: "2:34 PM", text: "this is the third time this week" },
    { from: "samira", time: "2:34 PM", text: "i don't like it" },
    { from: "maya", time: "2:35 PM", text: "i know" },
    { from: "maya", time: "2:35 PM", text: "i'm handling it" },
    { from: "samira", time: "2:35 PM", text: "handling what" },
    { from: "samira", time: "2:35 PM", text: "maya what's going on" },
    { from: "maya", time: "2:36 PM", text: "i can't explain right now" },
    { from: "samira", time: "2:36 PM", text: "why not" },
    { from: "maya", time: "2:37 PM", text: "because it's not safe" },
    { from: "samira", time: "2:37 PM", text: "WHAT" },
    { from: "samira", time: "2:37 PM", text: "maya what do you mean not safe" },
    { from: "samira", time: "2:38 PM", text: "maya" },
    { from: "samira", time: "2:38 PM", text: "MAYA" },
    { from: "samira", time: "2:38 PM", text: "answer me" },
    { from: "samira", time: "2:39 PM", text: "please" },
    { from: "samira", time: "2:39 PM", text: "i'm begging you" },
    { from: "samira", time: "2:39 PM", text: "just tell me you're okay" },
    { from: "samira", time: "2:40 PM", text: "please" },

    { day: "Friday 28 November" },
    { from: "samira", time: "11:42 PM", text: "maya please" },
    { from: "samira", time: "11:42 PM", text: "pick up" },
    { from: "samira", time: "11:43 PM", text: "dr sterling came into the shop again today" },
    { from: "samira", time: "11:43 PM", text: "he bought chamomile but he kept looking at the staff room door" },
    { from: "samira", time: "11:44 PM", text: "i am freaking out" },
    { from: "samira", time: "11:44 PM", text: "are u safe?" },
    { from: "samira", time: "11:45 PM", text: "maya" },
    { from: "samira", time: "11:45 PM", text: "maya" },
    { from: "samira", time: "11:45 PM", text: "please" },
    { from: "samira", time: "11:46 PM", text: "i'm scared" },
    { from: "samira", time: "11:46 PM", text: "i don't know what's happening" },
    { from: "samira", time: "11:47 PM", text: "but i know something is wrong" },
    { from: "samira", time: "11:47 PM", text: "please just answer" },
    { from: "samira", time: "11:47 PM", text: "please" }
  ]
};
