/* =========================================================
   CHAT: Mum
   ========================================================= */

window.CHATS_DATA.mum = {
  name: "Mum",
  bio: "the staircase remembers better than I do",
  avatarInitials: "M",
  avatarColor: "#5a4a4a",
  preview: "Your father is useless. Call me back right now.",
  time: "7:45 AM",
  unreadCount: 0,
  messages: [
    { day: "Sunday 23 November" },
    { from: "mum", time: "6:00 PM", text: "are you coming home this weekend or not" },
    { from: "mum", time: "6:00 PM", text: "your father is useless" },
    { from: "mum", time: "6:01 PM", text: "call me back right now" },
    { from: "mum", time: "6:02 PM", text: "maya" },
    { from: "mum", time: "6:03 PM", text: "i know you're reading these" },
    { from: "mum", time: "6:04 PM", text: "you always do this" },
    { from: "mum", time: "6:04 PM", text: "you ignore me for days and then act like nothing happened" },
    { from: "mum", time: "6:05 PM", text: "i'm your mother" },
    { from: "mum", time: "6:05 PM", text: "you can't just disappear" },
    { from: "maya", time: "6:30 PM", text: "i'm busy" },
    { from: "mum", time: "6:30 PM", text: "busy with what" },
    { from: "maya", time: "6:31 PM", text: "school" },
    { from: "mum", time: "6:31 PM", text: "you're always busy with school" },
    { from: "mum", time: "6:31 PM", text: "you never have time for your family" },
    { from: "maya", time: "6:32 PM", text: "you never ask" },
    { from: "mum", time: "6:32 PM", text: "i'm asking now" },
    { from: "maya", time: "6:33 PM", text: "too late" },
    { from: "mum", time: "6:33 PM", text: "don't you dare" },
    { from: "mum", time: "6:33 PM", text: "i am trying" },
    { from: "maya", time: "6:34 PM", text: "you're not" },
    { from: "mum", time: "6:34 PM", text: "maya" },
    { from: "mum", time: "6:35 PM", text: "maya" },
    { from: "mum", time: "6:36 PM", text: "fine" },
    { from: "mum", time: "6:36 PM", text: "ignore me" },
    { from: "mum", time: "6:37 PM", text: "see if i care" },

    { day: "Monday 24 November" },
    { from: "mum", time: "9:30 AM", text: "did you eat breakfast" },
    { from: "maya", time: "9:35 AM", text: "yes" },
    { from: "mum", time: "9:35 AM", text: "what did you eat" },
    { from: "maya", time: "9:36 AM", text: "food" },
    { from: "mum", time: "9:36 AM", text: "what food" },
    { from: "maya", time: "9:36 AM", text: "does it matter" },
    { from: "mum", time: "9:37 AM", text: "yes" },
    { from: "mum", time: "9:37 AM", text: "because i know you" },
    { from: "mum", time: "9:37 AM", text: "you probably skipped breakfast" },
    { from: "maya", time: "9:38 AM", text: "i didn't" },
    { from: "mum", time: "9:38 AM", text: "you're lying" },
    { from: "maya", time: "9:38 AM", text: "i'm not" },
    { from: "mum", time: "9:39 AM", text: "you always lie" },
    { from: "maya", time: "9:39 AM", text: "that's not fair" },
    { from: "mum", time: "9:39 AM", text: "life isn't fair" },
    { from: "mum", time: "9:40 AM", text: "call me when you get a chance" },
    { from: "mum", time: "9:40 AM", text: "i want to talk" },
    { from: "maya", time: "9:41 AM", text: "about what" },
    { from: "mum", time: "9:41 AM", text: "about everything" },
    { from: "mum", time: "9:41 AM", text: "about you" },
    { from: "mum", time: "9:41 AM", text: "about us" },
    { from: "maya", time: "9:42 AM", text: "there is no us" },
    { from: "mum", time: "9:42 AM", text: "maya" },
    { from: "mum", time: "9:42 AM", text: "don't say that" },
    { from: "maya", time: "9:43 AM", text: "it's true" },
    { from: "mum", time: "9:43 AM", text: "it's not" },
    { from: "maya", time: "9:43 AM", text: "you left" },
    { from: "mum", time: "9:44 AM", text: "i didn't leave" },
    { from: "maya", time: "9:44 AM", text: "you did" },
    { from: "mum", time: "9:44 AM", text: "that's not what happened" },
    { from: "maya", time: "9:45 AM", text: "that's exactly what happened" },
    { from: "mum", time: "9:45 AM", text: "maya" },
    { from: "mum", time: "9:46 AM", text: "maya" },
    { from: "mum", time: "9:46 AM", text: "please" },
    { from: "mum", time: "9:47 AM", text: "i'm sorry" },
    { from: "mum", time: "9:47 AM", text: "i'm sorry for everything" },
    { from: "mum", time: "9:48 AM", text: "just come home" },

    { day: "Tuesday 25 November" },
    { from: "mum", time: "7:45 AM", text: "your father called" },
    { from: "mum", time: "7:45 AM", text: "he said you haven't been answering him either" },
    { from: "maya", time: "7:50 AM", text: "i've been busy" },
    { from: "mum", time: "7:50 AM", text: "you're always busy" },
    { from: "mum", time: "7:50 AM", text: "what are you so busy with" },
    { from: "maya", time: "7:51 AM", text: "things" },
    { from: "mum", time: "7:51 AM", text: "what things" },
    { from: "maya", time: "7:51 AM", text: "just things" },
    { from: "mum", time: "7:52 AM", text: "maya" },
    { from: "mum", time: "7:52 AM", text: "why won't you talk to me" },
    { from: "maya", time: "7:53 AM", text: "because you don't listen" },
    { from: "mum", time: "7:53 AM", text: "i listen" },
    { from: "maya", time: "7:53 AM", text: "you don't" },
    { from: "maya", time: "7:54 AM", text: "you talk" },
    { from: "maya", time: "7:54 AM", text: "you tell me what to do" },
    { from: "maya", time: "7:54 AM", text: "you don't listen" },
    { from: "mum", time: "7:54 AM", text: "that's not true" },
    { from: "maya", time: "7:55 AM", text: "it is" },
    { from: "mum", time: "7:55 AM", text: "maya" },
    { from: "mum", time: "7:55 AM", text: "i'm trying" },
    { from: "maya", time: "7:56 AM", text: "try harder" },
    { from: "mum", time: "7:56 AM", text: "maya" },
    { from: "mum", time: "7:56 AM", text: "maya" },
    { from: "mum", time: "7:57 AM", text: "fine" },
    { from: "mum", time: "7:57 AM", text: "i'll stop" },
    { from: "mum", time: "7:57 AM", text: "but i love you" },
    { from: "mum", time: "7:58 AM", text: "even if you don't believe me" },
    { from: "mum", time: "7:58 AM", text: "i love you" }
  ]
};
