/* =========================================================
   CHAT: Filler threads (Day 1)
   Toby, Chloe, Benji, Henderson, Lily, Library, Pizza,
   Gran, Hale, Bio Project, Family.
   ========================================================= */

window.CHATS_DATA.toby = {
  name: "Toby Lin",
  bio: "by experiencing both victory and defeat, a man becomes a man",
  avatarInitials: "T",
  avatarColor: "#3a5a3a",
  preview: "did u watch the new episode yet",
  time: "Wed",
  unreadCount: 3,
  messages: [
    { day: "Saturday 18 October" },
    { from: "toby", time: "4:05 PM", text: "MAYA" },
    { from: "toby", time: "4:05 PM", text: "MAYA" },
    { from: "toby", time: "4:05 PM", text: "MAYA" },
    { from: "maya", time: "4:10 PM", text: "what" },
    { from: "toby", time: "4:10 PM", text: "watch one piece" },
    { from: "maya", time: "4:11 PM", text: "no" },
    { from: "toby", time: "4:11 PM", text: "please" },
    { from: "maya", time: "4:11 PM", text: "no" },
    { from: "toby", time: "4:12 PM", text: "please" },
    { from: "maya", time: "4:12 PM", text: "no" },
    { from: "toby", time: "4:12 PM", text: "PLEASE" },
    { from: "maya", time: "4:13 PM", text: "NO" },
    { from: "toby", time: "4:13 PM", text: "i'll never ask again" },
    { from: "maya", time: "4:14 PM", text: "you said that last week" },
    { from: "toby", time: "4:14 PM", text: "this time i mean it" },
    { from: "maya", time: "4:15 PM", text: "you didn't mean it last week" },
    { from: "toby", time: "4:15 PM", text: "i did" },
    { from: "maya", time: "4:15 PM", text: "you didn't" },
    { from: "toby", time: "4:16 PM", text: "i did" },
    { from: "maya", time: "4:16 PM", text: "you texted me 4 days later" },
    { from: "toby", time: "4:16 PM", text: "that was different" },
    { from: "maya", time: "4:17 PM", text: "it wasn't" },
    { from: "toby", time: "4:17 PM", text: "it was" },
    { from: "maya", time: "4:17 PM", text: "toby" },
    { from: "toby", time: "4:18 PM", text: "maya" },
    { from: "maya", time: "4:18 PM", text: "no" },
    { from: "toby", time: "4:18 PM", text: "😭" },

    { day: "Sunday 26 October" },
    { from: "toby", time: "9:10 PM", text: "ok new episode dropped" },
    { from: "toby", time: "9:10 PM", text: "it's peak" },
    { from: "toby", time: "9:10 PM", text: "you HAVE to watch it" },
    { from: "maya", time: "9:15 PM", text: "no" },
    { from: "toby", time: "9:15 PM", text: "maya" },
    { from: "maya", time: "9:16 PM", text: "no" },
    { from: "toby", time: "9:16 PM", text: "MAYA" },
    { from: "maya", time: "9:16 PM", text: "NO" },
    { from: "toby", time: "9:17 PM", text: "i'm going to keep asking" },
    { from: "maya", time: "9:17 PM", text: "i know" },
    { from: "toby", time: "9:17 PM", text: "forever" },
    { from: "maya", time: "9:18 PM", text: "i know" },
    { from: "toby", time: "9:18 PM", text: "until you watch it" },
    { from: "maya", time: "9:18 PM", text: "i know" },
    { from: "toby", time: "9:19 PM", text: "so just watch it" },
    { from: "maya", time: "9:19 PM", text: "no" },
    { from: "toby", time: "9:19 PM", text: "WHY" },
    { from: "maya", time: "9:20 PM", text: "because i don't want to" },
    { from: "toby", time: "9:20 PM", text: "that's not a reason" },
    { from: "maya", time: "9:20 PM", text: "it's my reason" },
    { from: "toby", time: "9:21 PM", text: "🙄" },

    { day: "Friday 7 November" },
    { from: "toby", time: "7:00 PM", text: "the new opening slaps" },
    { from: "toby", time: "7:00 PM", text: "SLAPS" },
    { from: "toby", time: "7:00 PM", text: "you'd know if you watched it" },
    { from: "maya", time: "7:15 PM", text: "i wouldn't" },
    { from: "toby", time: "7:15 PM", text: "you would" },
    { from: "maya", time: "7:16 PM", text: "i wouldn't" },
    { from: "toby", time: "7:16 PM", text: "you WOULD" },
    { from: "maya", time: "7:17 PM", text: "toby" },
    { from: "toby", time: "7:17 PM", text: "maya" },
    { from: "maya", time: "7:17 PM", text: "i'm not watching one piece" },
    { from: "toby", time: "7:18 PM", text: "you will one day" },
    { from: "maya", time: "7:18 PM", text: "i won't" },
    { from: "toby", time: "7:18 PM", text: "you will" },
    { from: "maya", time: "7:19 PM", text: "i won't" },
    { from: "toby", time: "7:19 PM", text: "you will" },
    { from: "maya", time: "7:19 PM", text: "TOBY" },
    { from: "toby", time: "7:20 PM", text: "MAYA" },
    { from: "maya", time: "7:20 PM", text: "🙄" },
    { from: "toby", time: "7:20 PM", text: "🙄" },
    { from: "toby", time: "7:21 PM", text: "also hi" },
    { from: "maya", time: "7:22 PM", text: "hi" },
    { from: "toby", time: "7:22 PM", text: "how are you" },
    { from: "maya", time: "7:23 PM", text: "fine" },
    { from: "toby", time: "7:23 PM", text: "cool" },
    { from: "toby", time: "7:23 PM", text: "watch one piece" },
    { from: "maya", time: "7:24 PM", text: "NO" },

    { day: "Saturday 15 November" },
    { from: "toby", time: "3:30 PM", text: "maya" },
    { from: "maya", time: "3:32 PM", text: "no" },
    { from: "toby", time: "3:32 PM", text: "i didn't say anything" },
    { from: "maya", time: "3:33 PM", text: "you were going to say one piece" },
    { from: "toby", time: "3:33 PM", text: "how did you know" },
    { from: "maya", time: "3:33 PM", text: "because you always say one piece" },
    { from: "toby", time: "3:34 PM", text: "that's fair" },
    { from: "maya", time: "3:34 PM", text: "🙄" },
    { from: "toby", time: "3:34 PM", text: "but also" },
    { from: "toby", time: "3:34 PM", text: "one piece" },
    { from: "maya", time: "3:35 PM", text: "NO" },
    { from: "toby", time: "3:35 PM", text: "😭" },

    { day: "Wednesday 26 November" },
    { from: "toby", time: "10:15 PM", text: "did u watch the new episode yet" },
    { from: "toby", time: "10:15 PM", text: "it's really good" },
    { from: "toby", time: "10:16 PM", text: "like REALLY good" },
    { from: "toby", time: "10:30 PM", text: "maya" },
    { from: "toby", time: "11:00 PM", text: "maya" }
  ]
};

window.CHATS_DATA.chloe = {
  name: "Chloe",
  bio: "someone forgot the chessboard",
  avatarInitials: "C",
  avatarColor: "#5a3a4a",
  preview: "pleeeeease just the last page",
  time: "Sat",
  unreadCount: 0,
  messages: [
    { day: "Monday 20 October" },
    { from: "chloe", time: "5:00 PM", text: "hey maya" },
    { from: "chloe", time: "5:00 PM", text: "maya" },
    { from: "chloe", time: "5:01 PM", text: "maya" },
    { from: "maya", time: "5:05 PM", text: "what" },
    { from: "chloe", time: "5:05 PM", text: "can you help me with the physics homework" },
    { from: "maya", time: "5:06 PM", text: "no" },
    { from: "chloe", time: "5:06 PM", text: "please" },
    { from: "maya", time: "5:06 PM", text: "no" },
    { from: "chloe", time: "5:06 PM", text: "please" },
    { from: "maya", time: "5:07 PM", text: "no" },
    { from: "chloe", time: "5:07 PM", text: "PLEASE" },
    { from: "maya", time: "5:07 PM", text: "chloe" },
    { from: "chloe", time: "5:08 PM", text: "maya" },
    { from: "maya", time: "5:08 PM", text: "no" },
    { from: "chloe", time: "5:08 PM", text: "why not" },
    { from: "maya", time: "5:09 PM", text: "because you never do your own work" },
    { from: "chloe", time: "5:09 PM", text: "i do" },
    { from: "maya", time: "5:09 PM", text: "you don't" },
    { from: "chloe", time: "5:10 PM", text: "i do" },
    { from: "maya", time: "5:10 PM", text: "last week you copied my entire essay" },
    { from: "chloe", time: "5:10 PM", text: "that was different" },
    { from: "maya", time: "5:11 PM", text: "it wasn't" },
    { from: "chloe", time: "5:11 PM", text: "it was" },
    { from: "maya", time: "5:11 PM", text: "chloe" },
    { from: "chloe", time: "5:12 PM", text: "maya" },
    { from: "maya", time: "5:12 PM", text: "no" },
    { from: "chloe", time: "5:12 PM", text: "FINE" },
    { from: "chloe", time: "5:13 PM", text: "🙄" },

    { day: "Wednesday 29 October" },
    { from: "chloe", time: "4:30 PM", text: "maya" },
    { from: "chloe", time: "4:30 PM", text: "maya" },
    { from: "chloe", time: "4:30 PM", text: "MAYA" },
    { from: "maya", time: "4:35 PM", text: "what" },
    { from: "chloe", time: "4:35 PM", text: "can you send me the notes from today" },
    { from: "maya", time: "4:36 PM", text: "no" },
    { from: "chloe", time: "4:36 PM", text: "why not" },
    { from: "maya", time: "4:36 PM", text: "because you were in class" },
    { from: "chloe", time: "4:37 PM", text: "i know but i didn't take notes" },
    { from: "maya", time: "4:37 PM", text: "that's your problem" },
    { from: "chloe", time: "4:37 PM", text: "maya" },
    { from: "chloe", time: "4:38 PM", text: "please" },
    { from: "chloe", time: "4:38 PM", text: "please" },
    { from: "chloe", time: "4:38 PM", text: "please" },
    { from: "maya", time: "4:39 PM", text: "no" },
    { from: "chloe", time: "4:39 PM", text: "PLEASEEEEEE" },
    { from: "maya", time: "4:40 PM", text: "no" },
    { from: "chloe", time: "4:40 PM", text: "i'll do anything" },
    { from: "maya", time: "4:41 PM", text: "no" },
    { from: "chloe", time: "4:41 PM", text: "i'll buy you coffee" },
    { from: "maya", time: "4:42 PM", text: "no" },
    { from: "chloe", time: "4:42 PM", text: "i'll buy you TWO coffees" },
    { from: "maya", time: "4:43 PM", text: "still no" },
    { from: "chloe", time: "4:43 PM", text: "maya you're so mean" },
    { from: "maya", time: "4:44 PM", text: "i know" },
    { from: "chloe", time: "4:44 PM", text: "🙄" },

    { day: "Saturday 9 November" },
    { from: "chloe", time: "11:00 AM", text: "ok so i need a favour" },
    { from: "maya", time: "11:05 AM", text: "no" },
    { from: "chloe", time: "11:05 AM", text: "i haven't even said what it is" },
    { from: "maya", time: "11:06 AM", text: "doesn't matter" },
    { from: "chloe", time: "11:06 AM", text: "maya" },
    { from: "maya", time: "11:06 AM", text: "chloe" },
    { from: "chloe", time: "11:07 AM", text: "please" },
    { from: "maya", time: "11:07 AM", text: "no" },
    { from: "chloe", time: "11:07 AM", text: "it's just one small thing" },
    { from: "maya", time: "11:08 AM", text: "your small things are never small" },
    { from: "chloe", time: "11:08 AM", text: "this one is" },
    { from: "maya", time: "11:08 AM", text: "what is it" },
    { from: "chloe", time: "11:09 AM", text: "can you do my half of the bio project" },
    { from: "maya", time: "11:09 AM", text: "no" },
    { from: "chloe", time: "11:09 AM", text: "maya" },
    { from: "maya", time: "11:10 AM", text: "no" },
    { from: "chloe", time: "11:10 AM", text: "please" },
    { from: "maya", time: "11:10 AM", text: "no" },
    { from: "chloe", time: "11:11 AM", text: "pleeeeease just the last page" },
    { from: "maya", time: "11:11 AM", text: "no" },
    { from: "chloe", time: "11:11 AM", text: "🙏" },
    { from: "maya", time: "11:12 AM", text: "no" },
    { from: "chloe", time: "11:12 AM", text: "i'll tell everyone you're cool" },
    { from: "maya", time: "11:13 AM", text: "i'm not cool" },
    { from: "chloe", time: "11:13 AM", text: "i'll tell them anyway" },
    { from: "maya", time: "11:13 AM", text: "no" },
    { from: "chloe", time: "11:14 AM", text: "FINE" },
    { from: "chloe", time: "11:14 AM", text: "i'll do it myself" },
    { from: "maya", time: "11:15 AM", text: "you won't" },
    { from: "chloe", time: "11:15 AM", text: "i will" },
    { from: "maya", time: "11:16 AM", text: "you won't" },
    { from: "chloe", time: "11:16 AM", text: "I WILL" },
    { from: "maya", time: "11:17 AM", text: "ok" },
    { from: "chloe", time: "11:17 AM", text: "..." },
    { from: "chloe", time: "11:17 AM", text: "can you at least check it when i'm done" },
    { from: "maya", time: "11:18 AM", text: "fine" },
    { from: "chloe", time: "11:18 AM", text: "thank you thank you thank you" },
    { from: "maya", time: "11:19 AM", text: "🙄" }
  ]
};

window.CHATS_DATA.benji = {
  name: "Benji",
  bio: "the fourth window stayed lit",
  avatarInitials: "B",
  avatarColor: "#4a4a3a",
  preview: "so are u going to the gala next month?",
  time: "Wed",
  unreadCount: 2,
  messages: [
    { day: "Sunday 13 October" },
    { from: "benji", time: "6:00 PM", text: "hey maya" },
    { from: "benji", time: "6:00 PM", text: "how are you" },
    { from: "maya", time: "6:15 PM", text: "fine" },
    { from: "benji", time: "6:15 PM", text: "that's good" },
    { from: "benji", time: "6:16 PM", text: "i'm good too" },
    { from: "benji", time: "6:16 PM", text: "i mean, you didn't ask, but i thought i'd say" },
    { from: "maya", time: "6:17 PM", text: "ok" },
    { from: "benji", time: "6:18 PM", text: "so um" },
    { from: "benji", time: "6:18 PM", text: "i was wondering" },
    { from: "benji", time: "6:19 PM", text: "are you going to the maths thing next weekend" },
    { from: "maya", time: "6:20 PM", text: "yes" },
    { from: "benji", time: "6:20 PM", text: "cool" },
    { from: "benji", time: "6:20 PM", text: "me too" },
    { from: "benji", time: "6:21 PM", text: "maybe we could sit together" },
    { from: "maya", time: "6:22 PM", text: "maybe" },
    { from: "benji", time: "6:22 PM", text: "ok" },
    { from: "benji", time: "6:22 PM", text: "cool" },
    { from: "benji", time: "6:22 PM", text: "cool cool cool" },
    { from: "maya", time: "6:23 PM", text: "🙄" },

    { day: "Tuesday 22 October" },
    { from: "benji", time: "4:30 PM", text: "hey maya" },
    { from: "benji", time: "4:30 PM", text: "i noticed you were wearing a new jumper today" },
    { from: "benji", time: "4:30 PM", text: "it looked nice" },
    { from: "maya", time: "4:45 PM", text: "thanks" },
    { from: "benji", time: "4:45 PM", text: "yeah" },
    { from: "benji", time: "4:46 PM", text: "so um" },
    { from: "benji", time: "4:46 PM", text: "do you like" },
    { from: "benji", time: "4:46 PM", text: "like like anyone" },
    { from: "maya", time: "4:50 PM", text: "no" },
    { from: "benji", time: "4:50 PM", text: "oh" },
    { from: "benji", time: "4:50 PM", text: "ok" },
    { from: "benji", time: "4:50 PM", text: "cool" },
    { from: "benji", time: "4:51 PM", text: "i was just wondering" },
    { from: "benji", time: "4:51 PM", text: "for no reason" },
    { from: "benji", time: "4:51 PM", text: "just asking" },
    { from: "maya", time: "4:52 PM", text: "ok" },
    { from: "benji", time: "4:52 PM", text: "ok" },
    { from: "benji", time: "4:52 PM", text: "cool" },
    { from: "maya", time: "4:53 PM", text: "🙄" },

    { day: "Friday 1 November" },
    { from: "benji", time: "7:00 PM", text: "hey maya" },
    { from: "benji", time: "7:00 PM", text: "i know you don't really like talking much" },
    { from: "benji", time: "7:01 PM", text: "but i was thinking" },
    { from: "benji", time: "7:01 PM", text: "and i wanted to ask" },
    { from: "benji", time: "7:02 PM", text: "would you maybe want to" },
    { from: "benji", time: "7:02 PM", text: "get coffee sometime" },
    { from: "benji", time: "7:02 PM", text: "like just us" },
    { from: "benji", time: "7:03 PM", text: "no pressure" },
    { from: "benji", time: "7:03 PM", text: "just coffee" },
    { from: "maya", time: "7:15 PM", text: "no" },
    { from: "benji", time: "7:15 PM", text: "oh" },
    { from: "benji", time: "7:15 PM", text: "ok" },
    { from: "benji", time: "7:16 PM", text: "that's fine" },
    { from: "benji", time: "7:16 PM", text: "totally fine" },
    { from: "benji", time: "7:16 PM", text: "sorry for asking" },
    { from: "maya", time: "7:17 PM", text: "it's fine" },
    { from: "benji", time: "7:17 PM", text: "ok" },
    { from: "benji", time: "7:17 PM", text: "cool" },
    { from: "benji", time: "7:18 PM", text: "i'll see you at school" },
    { from: "maya", time: "7:19 PM", text: "ok" },

    { day: "Wednesday 20 November" },
    { from: "benji", time: "8:30 PM", text: "hey" },
    { from: "benji", time: "8:30 PM", text: "so i know you said no to coffee" },
    { from: "benji", time: "8:31 PM", text: "which is fine" },
    { from: "benji", time: "8:31 PM", text: "totally fine" },
    { from: "benji", time: "8:32 PM", text: "but i was wondering" },
    { from: "benji", time: "8:33 PM", text: "so are u going to the gala next month?" },
    { from: "benji", time: "8:33 PM", text: "i heard the whole school is going" },
    { from: "benji", time: "8:34 PM", text: "it might be fun" },
    { from: "benji", time: "8:34 PM", text: "maybe we could go together" },
    { from: "benji", time: "8:35 PM", text: "like as friends" },
    { from: "benji", time: "8:35 PM", text: "or not" },
    { from: "benji", time: "8:36 PM", text: "no pressure" },
    { from: "benji", time: "8:36 PM", text: "just wondering" }
  ]
};

window.CHATS_DATA.henderson = {
  name: "Mr. Henderson",
  bio: "the answer was technically 17",
  avatarInitials: "H",
  avatarColor: "#3a4a5a",
  preview: "Maya, your coursework is pending.",
  time: "Fri",
  unreadCount: 0,
  messages: [
    { day: "Monday 4 November" },
    { from: "henderson", time: "11:00 AM", text: "Maya, I noticed you have not submitted your coursework." },
    { from: "maya", time: "11:30 AM", text: "I know. I'll do it this week." },
    { from: "henderson", time: "11:31 AM", text: "The deadline was Friday." },
    { from: "maya", time: "11:32 AM", text: "I know." },
    { from: "henderson", time: "11:32 AM", text: "Maya, this is unlike you." },
    { from: "maya", time: "11:33 AM", text: "I've been busy." },
    { from: "henderson", time: "11:33 AM", text: "With what, exactly?" },
    { from: "maya", time: "11:34 AM", text: "Things." },
    { from: "henderson", time: "11:34 AM", text: "Maya." },
    { from: "maya", time: "11:35 AM", text: "I'll submit it this week." },
    { from: "henderson", time: "11:35 AM", text: "I'll hold you to that." },
    { from: "maya", time: "11:36 AM", text: "You will." },
    { from: "henderson", time: "11:36 AM", text: "Good." },

    { day: "Friday 15 November" },
    { from: "henderson", time: "9:00 AM", text: "Maya, your coursework is still pending." },
    { from: "maya", time: "9:20 AM", text: "I'll do it this weekend." },
    { from: "henderson", time: "9:20 AM", text: "You said that last week." },
    { from: "maya", time: "9:21 AM", text: "I know." },
    { from: "henderson", time: "9:21 AM", text: "Is everything alright?" },
    { from: "maya", time: "9:22 AM", text: "Yes." },
    { from: "henderson", time: "9:22 AM", text: "You can talk to me if something is wrong." },
    { from: "maya", time: "9:23 AM", text: "I know. Thank you." },
    { from: "henderson", time: "9:23 AM", text: "Of course." }
  ]
};

window.CHATS_DATA.lily = {
  name: "Lily",
  bio: "the bicycle knew the way home",
  avatarInitials: "L",
  avatarColor: "#5a4a3a",
  preview: "thank u for the help with fractions!!",
  time: "Sun",
  unreadCount: 0,
  messages: [
    { day: "Saturday 12 October" },
    { from: "lily", time: "3:30 PM", text: "hi maya" },
    { from: "lily", time: "3:30 PM", text: "are you free today" },
    { from: "maya", time: "3:45 PM", text: "yes" },
    { from: "lily", time: "3:45 PM", text: "can you help me with fractions again" },
    { from: "maya", time: "3:46 PM", text: "come over at 4" },
    { from: "lily", time: "3:46 PM", text: "ok!!" },
    { from: "lily", time: "3:46 PM", text: "thank you!!!!" },
    { from: "maya", time: "3:47 PM", text: "no problem" },

    { day: "Saturday 26 October" },
    { from: "lily", time: "5:00 PM", text: "maya" },
    { from: "lily", time: "5:00 PM", text: "i got a 78 on my maths test" },
    { from: "maya", time: "5:15 PM", text: "good" },
    { from: "lily", time: "5:15 PM", text: "you helped" },
    { from: "maya", time: "5:16 PM", text: "you did the work" },
    { from: "lily", time: "5:16 PM", text: "but you taught me" },
    { from: "maya", time: "5:17 PM", text: "you still did the work" },
    { from: "lily", time: "5:17 PM", text: "thank u for the help with fractions!!" },
    { from: "maya", time: "5:18 PM", text: "anytime" },
    { from: "lily", time: "5:18 PM", text: "you're the best" },
    { from: "maya", time: "5:19 PM", text: "i'm not" },
    { from: "lily", time: "5:19 PM", text: "you are" },
    { from: "maya", time: "5:20 PM", text: "🙄" },
    { from: "lily", time: "5:20 PM", text: "😊" },

    { day: "Sunday 17 November" },
    { from: "lily", time: "6:30 PM", text: "maya" },
    { from: "lily", time: "6:30 PM", text: "are you ok" },
    { from: "lily", time: "6:31 PM", text: "you seem sad lately" },
    { from: "maya", time: "6:45 PM", text: "i'm fine" },
    { from: "lily", time: "6:45 PM", text: "ok" },
    { from: "lily", time: "6:46 PM", text: "if you want to talk i'm here" },
    { from: "maya", time: "6:50 PM", text: "thank you lily" },
    { from: "lily", time: "6:50 PM", text: "❤️" },
    { from: "maya", time: "6:51 PM", text: "❤️" }
  ]
};

window.CHATS_DATA.library = {
  name: "Ashcombe Library",
  bio: "the missing page was page seven",
  avatarInitials: "A",
  avatarColor: "#3a3a4a",
  preview: "Your loan for 'Advanced Calculus' is overdue.",
  time: "Mon",
  unreadCount: 0,
  messages: [
    { day: "Monday 7 October" },
    { from: "library", time: "10:00 AM", text: "Your loan for 'Introduction to Number Theory' is due in 3 days." },
    { from: "library", time: "10:00 AM", text: "Renew online or return to the library." },

    { day: "Thursday 10 October" },
    { from: "library", time: "10:00 AM", text: "Your loan for 'Introduction to Number Theory' is overdue." },
    { from: "library", time: "10:00 AM", text: "Please return it as soon as possible." },

    { day: "Monday 21 October" },
    { from: "library", time: "10:00 AM", text: "Your loan for 'Advanced Calculus' is overdue." },
    { from: "library", time: "10:00 AM", text: "Please return it as soon as possible." },

    { day: "Monday 4 November" },
    { from: "library", time: "10:00 AM", text: "Your loan for 'Advanced Calculus' is still overdue." },
    { from: "library", time: "10:00 AM", text: "A fine of £3.50 has been added to your account." },

    { day: "Monday 18 November" },
    { from: "library", time: "10:00 AM", text: "Your loan for 'Advanced Calculus' is still overdue." },
    { from: "library", time: "10:00 AM", text: "Please return it. We miss it." }
  ]
};

window.CHATS_DATA.pizza = {
  name: "Pizza Express",
  bio: "",
  avatarInitials: "P",
  avatarColor: "#5a2a2a",
  preview: "Your order is out for delivery.",
  time: "Mon",
  unreadCount: 0,
  messages: [
    { day: "Friday 11 October" },
    { from: "pizza", time: "7:15 PM", text: "Thank you for your order." },
    { from: "pizza", time: "7:15 PM", text: "1 x Margherita, 1 x Garlic Bread." },
    { from: "pizza", time: "7:45 PM", text: "Your order is out for delivery." },
    { from: "pizza", time: "8:15 PM", text: "Your order has been delivered. Enjoy." },

    { day: "Tuesday 22 October" },
    { from: "pizza", time: "7:30 PM", text: "Thank you for your order." },
    { from: "pizza", time: "7:30 PM", text: "1 x Margherita, 1 x Garlic Bread." },
    { from: "pizza", time: "8:00 PM", text: "Your order is out for delivery." },
    { from: "pizza", time: "8:30 PM", text: "Your order has been delivered. Enjoy." },

    { day: "Wednesday 30 October" },
    { from: "pizza", time: "6:50 PM", text: "Thank you for your order." },
    { from: "pizza", time: "6:50 PM", text: "1 x Margherita, 1 x Garlic Bread." },
    { from: "pizza", time: "7:20 PM", text: "Your order is out for delivery." },

    { day: "Saturday 9 November" },
    { from: "pizza", time: "8:00 PM", text: "Thank you for your order." },
    { from: "pizza", time: "8:00 PM", text: "1 x Margherita, 1 x Garlic Bread." },
    { from: "pizza", time: "8:30 PM", text: "Your order is out for delivery." },
    { from: "pizza", time: "9:00 PM", text: "Your order has been delivered. Enjoy." },

    { day: "Tuesday 19 November" },
    { from: "pizza", time: "7:00 PM", text: "Thank you for your order." },
    { from: "pizza", time: "7:00 PM", text: "1 x Margherita, 1 x Garlic Bread." },
    { from: "pizza", time: "7:30 PM", text: "Your order is out for delivery." },
    { from: "pizza", time: "8:00 PM", text: "Your order has been delivered. Enjoy." },

    { day: "Friday 22 November" },
    { from: "pizza", time: "7:45 PM", text: "Thank you for your order." },
    { from: "pizza", time: "7:45 PM", text: "1 x Margherita, 1 x Garlic Bread." },
    { from: "pizza", time: "8:15 PM", text: "Your order is out for delivery." },
    { from: "pizza", time: "8:45 PM", text: "Your order has been delivered. Enjoy." },

    { day: "Monday 25 November" },
    { from: "pizza", time: "7:15 PM", text: "Thank you for your order." },
    { from: "pizza", time: "7:15 PM", text: "1 x Margherita, 1 x Garlic Bread." },
    { from: "pizza", time: "7:45 PM", text: "Your order is out for delivery." }
  ]
};

window.CHATS_DATA.gran = {
  name: "Gran",
  bio: "keeping small appointments with dusk",
  avatarInitials: "G",
  avatarColor: "#4a3a3a",
  preview: "Please call your mother.",
  time: "Sun",
  unreadCount: 0,
  messages: [
    { day: "Sunday 15 September" },
    { from: "gran", time: "3:00 PM", text: "Maya, dear, it's your grandmother." },
    { from: "gran", time: "3:00 PM", text: "Please call your mother." },
    { from: "gran", time: "3:01 PM", text: "She's worried about you." },

    { day: "Sunday 6 October" },
    { from: "gran", time: "2:30 PM", text: "Maya, dear." },
    { from: "gran", time: "2:30 PM", text: "I know things are difficult." },
    { from: "gran", time: "2:31 PM", text: "But please call your mother." },

    { day: "Sunday 3 November" },
    { from: "gran", time: "4:00 PM", text: "Maya, dear." },
    { from: "gran", time: "4:00 PM", text: "Are you eating?" },
    { from: "gran", time: "4:01 PM", text: "Please call your mother." },

    { day: "Sunday 24 November" },
    { from: "gran", time: "5:00 PM", text: "Maya, dear." },
    { from: "gran", time: "5:00 PM", text: "I hope you're well." },
    { from: "gran", time: "5:01 PM", text: "Please call your mother." },
    { from: "gran", time: "5:02 PM", text: "She loves you, even if she's not good at showing it." },
    { from: "gran", time: "5:02 PM", text: "I love you too." }
  ]
};

window.CHATS_DATA.hale = {
  name: "Mr. Hale",
  bio: "an appointment with the old school clock",
  avatarInitials: "H",
  avatarColor: "#3a3a3a",
  preview: "I saw Dr. Sterling today. Be careful, Maya.",
  time: "Fri",
  unreadCount: 1,
  messages: [
    { day: "Tuesday 15 October" },
    { from: "hale", time: "4:00 PM", text: "Hello Maya." },
    { from: "hale", time: "4:00 PM", text: "I heard you've been doing well at Fenwick." },
    { from: "hale", time: "4:01 PM", text: "I always knew you would." },
    { from: "maya", time: "4:15 PM", text: "Thank you, Mr. Hale." },
    { from: "hale", time: "4:15 PM", text: "How is your mathematics?" },
    { from: "maya", time: "4:16 PM", text: "Good." },
    { from: "hale", time: "4:16 PM", text: "Good." },
    { from: "hale", time: "4:17 PM", text: "You know, I always thought you were the brightest student I ever taught." },
    { from: "maya", time: "4:18 PM", text: "That's kind of you to say." },
    { from: "hale", time: "4:18 PM", text: "It's not kindness. It's fact." },
    { from: "maya", time: "4:19 PM", text: "Thank you." },

    { day: "Friday 1 November" },
    { from: "hale", time: "6:00 PM", text: "Maya, may I ask you something?" },
    { from: "maya", time: "6:15 PM", text: "Of course." },
    { from: "hale", time: "6:15 PM", text: "Are you alright?" },
    { from: "maya", time: "6:16 PM", text: "Yes." },
    { from: "hale", time: "6:16 PM", text: "You seem different lately." },
    { from: "maya", time: "6:17 PM", text: "I'm fine." },
    { from: "hale", time: "6:17 PM", text: "If you ever need to talk, you know where to find me." },
    { from: "maya", time: "6:18 PM", text: "I know. Thank you." },

    { day: "Thursday 21 November" },
    { from: "hale", time: "3:30 PM", text: "Maya." },
    { from: "hale", time: "3:30 PM", text: "I saw you in town yesterday." },
    { from: "hale", time: "3:31 PM", text: "You looked like you were in a hurry." },
    { from: "maya", time: "3:45 PM", text: "I was." },
    { from: "hale", time: "3:45 PM", text: "Is everything alright?" },
    { from: "maya", time: "3:46 PM", text: "Yes." },
    { from: "hale", time: "3:46 PM", text: "Maya." },
    { from: "maya", time: "3:47 PM", text: "I'm fine, Mr. Hale. Really." },
    { from: "hale", time: "3:47 PM", text: "Alright." },
    { from: "hale", time: "3:48 PM", text: "But please be careful." },

    { day: "Friday 22 November" },
    { from: "hale", time: "11:00 AM", text: "Maya." },
    { from: "hale", time: "11:00 AM", text: "I saw Dr. Sterling today. Be careful, Maya." }
  ]
};

window.CHATS_DATA.bioproject = {
  name: "Bio Project Group",
  bio: "a paragraph nobody asked for",
  avatarInitials: "B",
  avatarColor: "#4a4a4a",
  preview: "(Chloe) maya did u print the pdf",
  time: "Nov",
  unreadCount: 0,
  messages: [
    { day: "Monday 11 November" },
    { from: "chloe", name: "Chloe", time: "5:00 PM", text: "ok so we need to divide the work" },
    { from: "chloe", name: "Chloe", time: "5:00 PM", text: "i'll do intro" },
    { from: "chloe", name: "Chloe", time: "5:01 PM", text: "someone else do body" },
    { from: "random", name: "Random Classmate", time: "5:05 PM", text: "i'll do body" },
    { from: "chloe", name: "Chloe", time: "5:05 PM", text: "cool" },
    { from: "chloe", name: "Chloe", time: "5:05 PM", text: "maya you do conclusion" },
    { from: "maya", name: "Maya", time: "5:10 PM", text: "ok" },
    { from: "chloe", name: "Chloe", time: "5:10 PM", text: "great" },
    { from: "chloe", name: "Chloe", time: "5:11 PM", text: "when can we meet" },
    { from: "random", name: "Random Classmate", time: "5:15 PM", text: "not this week" },
    { from: "chloe", name: "Chloe", time: "5:15 PM", text: "next week" },
    { from: "random", name: "Random Classmate", time: "5:16 PM", text: "yeah" },
    { from: "maya", name: "Maya", time: "5:20 PM", text: "sure" },

    { day: "Friday 15 November" },
    { from: "chloe", name: "Chloe", time: "4:00 PM", text: "ok so i haven't started" },
    { from: "random", name: "Random Classmate", time: "4:05 PM", text: "me neither" },
    { from: "chloe", name: "Chloe", time: "4:06 PM", text: "maya have you" },
    { from: "maya", name: "Maya", time: "4:10 PM", text: "yes" },
    { from: "chloe", name: "Chloe", time: "4:10 PM", text: "of course you have" },
    { from: "maya", name: "Maya", time: "4:11 PM", text: "🙄" },
    { from: "chloe", name: "Chloe", time: "4:11 PM", text: "can you send me yours so i can see the format" },
    { from: "maya", name: "Maya", time: "4:12 PM", text: "no" },
    { from: "chloe", name: "Chloe", time: "4:12 PM", text: "maya" },
    { from: "maya", name: "Maya", time: "4:12 PM", text: "no" },
    { from: "chloe", name: "Chloe", time: "4:13 PM", text: "please" },
    { from: "maya", name: "Maya", time: "4:13 PM", text: "no" },
    { from: "chloe", name: "Chloe", time: "4:13 PM", text: "FINE" },
    { from: "maya", name: "Maya", time: "4:14 PM", text: "🙄" },

    { day: "Monday 18 November" },
    { from: "chloe", name: "Chloe", time: "6:00 PM", text: "maya did u print the pdf" },
    { from: "maya", name: "Maya", time: "6:10 PM", text: "yes" },
    { from: "chloe", name: "Chloe", time: "6:10 PM", text: "can you print mine too" },
    { from: "maya", name: "Maya", time: "6:11 PM", text: "no" },
    { from: "chloe", name: "Chloe", time: "6:11 PM", text: "maya" },
    { from: "maya", name: "Maya", time: "6:11 PM", text: "no" },
    { from: "chloe", name: "Chloe", time: "6:12 PM", text: "PLEASE" },
    { from: "maya", name: "Maya", time: "6:12 PM", text: "no" },
    { from: "chloe", name: "Chloe", time: "6:13 PM", text: "fine i'll do it myself" },
    { from: "maya", name: "Maya", time: "6:13 PM", text: "you won't" },
    { from: "chloe", name: "Chloe", time: "6:14 PM", text: "i will" },
    { from: "maya", name: "Maya", time: "6:14 PM", text: "ok" },
    { from: "chloe", name: "Chloe", time: "6:15 PM", text: "..." },
    { from: "chloe", name: "Chloe", time: "6:15 PM", text: "can you print mine" },
    { from: "maya", name: "Maya", time: "6:16 PM", text: "no" },
    { from: "chloe", name: "Chloe", time: "6:16 PM", text: "😭" }
  ]
};

window.CHATS_DATA.family = {
  name: "Family",
  bio: "subject to interpretation",
  avatarInitials: "F",
  avatarColor: "#4a3a3a",
  preview: "(Dad) Happy Birthday Maya.",
  time: "Sep",
  unreadCount: 0,
  messages: [
    { day: "Tuesday 3 January 2023" },
    { from: "mum", name: "Mum", time: "7:00 PM", text: "Maya, please tell your father to stop texting me." },
    { from: "dad", name: "Dad", time: "7:02 PM", text: "I'm not texting you. I'm texting Maya." },
    { from: "mum", name: "Mum", time: "7:03 PM", text: "You're in the same chat." },
    { from: "dad", name: "Dad", time: "7:03 PM", text: "I know." },
    { from: "mum", name: "Mum", time: "7:04 PM", text: "Then stop." },
    { from: "dad", name: "Dad", time: "7:04 PM", text: "No." },
    { from: "mum", name: "Mum", time: "7:05 PM", text: "This is why I left." },
    { from: "dad", name: "Dad", time: "7:05 PM", text: "This is not the place." },
    { from: "mum", name: "Mum", time: "7:06 PM", text: "Then where is?" },
    { from: "dad", name: "Dad", time: "7:06 PM", text: "Not here." },
    { from: "mum", name: "Mum", time: "7:07 PM", text: "Typical." },
    { from: "dad", name: "Dad", time: "7:07 PM", text: "Stop." },
    { from: "mum", name: "Mum", time: "7:08 PM", text: "You stop." },

    { day: "Tuesday 8 August 2023" },
    { from: "dad", name: "Dad", time: "6:00 PM", text: "Maya, are you coming to your mum's this weekend?" },
    { from: "maya", name: "Maya", time: "6:15 PM", text: "yes" },
    { from: "dad", name: "Dad", time: "6:15 PM", text: "Good." },
    { from: "mum", name: "Mum", time: "6:20 PM", text: "She's coming to mine, not yours." },
    { from: "dad", name: "Dad", time: "6:20 PM", text: "I didn't say she was coming to mine." },
    { from: "mum", name: "Mum", time: "6:21 PM", text: "You implied it." },
    { from: "dad", name: "Dad", time: "6:21 PM", text: "I didn't." },
    { from: "mum", name: "Mum", time: "6:22 PM", text: "You did." },
    { from: "dad", name: "Dad", time: "6:22 PM", text: "Fine." },
    { from: "mum", name: "Mum", time: "6:23 PM", text: "Fine." },

    { day: "Thursday 21 September 2023" },
    { from: "dad", name: "Dad", time: "9:00 AM", text: "Happy Birthday Maya." },
    { from: "mum", name: "Mum", time: "9:01 AM", text: "Happy birthday, sweetheart." },
    { from: "dad", name: "Dad", time: "9:05 AM", text: "I hope you have a good day." },
    { from: "mum", name: "Mum", time: "9:06 AM", text: "We're having a cake at 6." },
    { from: "dad", name: "Dad", time: "9:07 AM", text: "I wasn't invited." },
    { from: "mum", name: "Mum", time: "9:07 AM", text: "You weren't." },
    { from: "dad", name: "Dad", time: "9:08 AM", text: "Typical." },
    { from: "mum", name: "Mum", time: "9:08 AM", text: "Stop." },
    { from: "dad", name: "Dad", time: "9:09 AM", text: "You stop." },

    { day: "Monday 1 January 2024" },
    { from: "dad", name: "Dad", time: "12:05 AM", text: "Happy New Year Maya." },
    { from: "mum", name: "Mum", time: "12:06 AM", text: "Happy New Year, sweetheart." },

    { day: "Thursday 21 September 2024" },
    { from: "dad", name: "Dad", time: "9:00 AM", text: "Happy Birthday Maya." },
    { from: "mum", name: "Mum", time: "9:01 AM", text: "Happy birthday, my love." },

    { day: "Sunday 21 September 2025" },
    { from: "dad", name: "Dad", time: "9:00 AM", text: "Happy Birthday Maya." }
  ]
};
