/* =========================================================
   CHAT: Julian Thorne
   ========================================================= */

window.CHATS_DATA.julian = {
  name: "Julian Thorne",
  bio: "I skipped to the interesting part",
  avatarInitials: "J",
  avatarColor: "#4a3a5a",
  preview: "You are making a massive mistake, Maya.",
  time: "3:33 PM",
  unreadCount: 0,
  messages: [
    { day: "Saturday 22 November" },
    { from: "julian", time: "4:05 PM", text: "Did you seriously take a picture of the ledger?" },
    { from: "maya", time: "4:06 PM", text: "You know I did." },
    { from: "julian", time: "4:06 PM", text: "Delete it. Sterling is already asking questions." },
    { from: "maya", time: "4:07 PM", text: "No." },
    { from: "julian", time: "4:07 PM", text: "Maya" },
    { from: "julian", time: "4:07 PM", text: "This is not a game" },
    { from: "maya", time: "4:08 PM", text: "I know it's not" },
    { from: "julian", time: "4:08 PM", text: "Then delete it" },
    { from: "maya", time: "4:09 PM", text: "No" },
    { from: "julian", time: "4:09 PM", text: "You are making a massive mistake, Maya." },
    { from: "maya", time: "4:10 PM", text: "Maybe" },
    { from: "maya", time: "4:10 PM", text: "But it's my mistake to make" },
    { from: "julian", time: "4:10 PM", text: "You're going to get yourself killed" },
    { from: "maya", time: "4:11 PM", text: "Probably" },
    { from: "julian", time: "4:11 PM", text: "That's not funny" },
    { from: "maya", time: "4:11 PM", text: "I wasn't joking" },
    { from: "julian", time: "4:12 PM", text: "Maya please" },
    { from: "maya", time: "4:12 PM", text: "Why do you care" },
    { from: "julian", time: "4:13 PM", text: "Because I do" },
    { from: "maya", time: "4:13 PM", text: "That's not an answer" },
    { from: "julian", time: "4:13 PM", text: "It's the only one I have" },
    { from: "maya", time: "4:14 PM", text: "Then it's not good enough" },
    { from: "julian", time: "4:14 PM", text: "Fine" },
    { from: "julian", time: "4:14 PM", text: "Don't listen to me" },
    { from: "julian", time: "4:14 PM", text: "See what happens" },
    { from: "maya", time: "4:15 PM", text: "I will" },

    { day: "Sunday 23 November" },
    { from: "julian", time: "11:15 AM", text: "I saw you talking to Sterling" },
    { from: "julian", time: "11:15 AM", text: "What did you tell him" },
    { from: "maya", time: "11:16 AM", text: "Nothing" },
    { from: "julian", time: "11:16 AM", text: "Don't lie to me" },
    { from: "maya", time: "11:17 AM", text: "I'm not lying" },
    { from: "julian", time: "11:17 AM", text: "You're always lying" },
    { from: "maya", time: "11:18 AM", text: "Look who's talking" },
    { from: "julian", time: "11:18 AM", text: "What's that supposed to mean" },
    { from: "maya", time: "11:19 AM", text: "You know exactly what it means" },
    { from: "julian", time: "11:19 AM", text: "I don't" },
    { from: "maya", time: "11:19 AM", text: "You do" },
    { from: "maya", time: "11:19 AM", text: "You're just pretending you don't" },
    { from: "julian", time: "11:20 AM", text: "Maya" },
    { from: "maya", time: "11:20 AM", text: "Julian" },
    { from: "maya", time: "11:20 AM", text: "Stop texting me" },
    { from: "julian", time: "11:21 AM", text: "No" },
    { from: "maya", time: "11:21 AM", text: "Stop" },
    { from: "julian", time: "11:21 AM", text: "I can't" },
    { from: "maya", time: "11:22 AM", text: "Why not" },
    { from: "julian", time: "11:22 AM", text: "Because I'm worried about you" },
    { from: "maya", time: "11:23 AM", text: "Don't be" },
    { from: "julian", time: "11:23 AM", text: "Too late" },
    { from: "maya", time: "11:23 AM", text: "Then that's your problem" },
    { from: "julian", time: "11:24 AM", text: "You're impossible" },
    { from: "maya", time: "11:24 AM", text: "I know" },

    { day: "Monday 24 November" },
    { from: "julian", time: "3:20 PM", text: "I know what you're doing" },
    { from: "maya", time: "3:21 PM", text: "Good for you" },
    { from: "julian", time: "3:21 PM", text: "You're going to get caught" },
    { from: "maya", time: "3:22 PM", text: "Maybe" },
    { from: "julian", time: "3:22 PM", text: "And then what" },
    { from: "maya", time: "3:22 PM", text: "Then I deal with it" },
    { from: "julian", time: "3:23 PM", text: "You can't deal with Sterling" },
    { from: "maya", time: "3:23 PM", text: "Watch me" },
    { from: "julian", time: "3:23 PM", text: "Maya" },
    { from: "maya", time: "3:24 PM", text: "Julian" },
    { from: "maya", time: "3:24 PM", text: "Stop" },
    { from: "maya", time: "3:24 PM", text: "Just stop" },
    { from: "julian", time: "3:24 PM", text: "I can't" },
    { from: "julian", time: "3:25 PM", text: "I can't just watch you do this" },
    { from: "maya", time: "3:25 PM", text: "Then don't watch" },
    { from: "julian", time: "3:25 PM", text: "That's not fair" },
    { from: "maya", time: "3:26 PM", text: "Life isn't fair" },
    { from: "julian", time: "3:26 PM", text: "You sound like your mother" },
    { from: "maya", time: "3:26 PM", text: "Don't" },
    { from: "julian", time: "3:27 PM", text: "Sorry" },
    { from: "maya", time: "3:27 PM", text: "Don't ever say that again" },
    { from: "julian", time: "3:27 PM", text: "I'm sorry" },
    { from: "maya", time: "3:28 PM", text: "Goodbye Julian" },
    { from: "julian", time: "3:28 PM", text: "Maya" },
    { from: "julian", time: "3:29 PM", text: "Maya" },
    { from: "julian", time: "3:29 PM", text: "Please" },
    { from: "julian", time: "3:30 PM", text: "I'm sorry" },
    { from: "julian", time: "3:30 PM", text: "I didn't mean it" },
    { from: "julian", time: "3:31 PM", text: "Maya" },
    { from: "julian", time: "3:32 PM", text: "Please answer" },
    { from: "julian", time: "3:33 PM", text: "I'm sorry" }
  ]
};
