/* =========================================================
   CHAT: Homies (group)
   ========================================================= */

window.CHATS_DATA.homies = {
  name: "Homies",
  bio: "operating without adult supervision",
  avatarInitials: "H",
  avatarColor: "#5a5a3a",
  preview: "(Chloe) omg wait who said that",
  time: "11:14 PM",
  unreadCount: 47,
  messages: [
    { day: "Saturday 15 November" },
    { from: "chloe", name: "Chloe", time: "6:12 PM", text: "ok who's coming to the thing on saturday" },
    { from: "samira", name: "Samira", time: "6:13 PM", text: "what thing" },
    { from: "chloe", name: "Chloe", time: "6:13 PM", text: "the thing" },
    { from: "samira", name: "Samira", time: "6:13 PM", text: "WHAT THING" },
    { from: "chloe", name: "Chloe", time: "6:14 PM", text: "the party at kyle's" },
    { from: "samira", name: "Samira", time: "6:14 PM", text: "oh that thing" },
    { from: "samira", name: "Samira", time: "6:14 PM", text: "no" },
    { from: "chloe", name: "Chloe", time: "6:15 PM", text: "why not" },
    { from: "samira", name: "Samira", time: "6:15 PM", text: "because kyle is a walking red flag" },
    { from: "benji", name: "Benji", time: "6:16 PM", text: "i'll come" },
    { from: "chloe", name: "Chloe", time: "6:16 PM", text: "of course you will benji" },
    { from: "benji", name: "Benji", time: "6:17 PM", text: "what does that mean" },
    { from: "chloe", name: "Chloe", time: "6:17 PM", text: "nothing" },
    { from: "benji", name: "Benji", time: "6:17 PM", text: "it meant something" },
    { from: "chloe", name: "Chloe", time: "6:18 PM", text: "it didn't" },
    { from: "benji", name: "Benji", time: "6:18 PM", text: "chloe" },
    { from: "chloe", name: "Chloe", time: "6:18 PM", text: "benji" },
    { from: "toby", name: "Toby", time: "6:20 PM", text: "guys i just watched the new one piece episode" },
    { from: "toby", name: "Toby", time: "6:20 PM", text: "holy shit" },
    { from: "toby", name: "Toby", time: "6:20 PM", text: "HOLY SHIT" },
    { from: "chloe", name: "Chloe", time: "6:21 PM", text: "toby please" },
    { from: "toby", name: "Toby", time: "6:21 PM", text: "YOU DON'T UNDERSTAND" },
    { from: "samira", name: "Samira", time: "6:22 PM", text: "we never do" },
    { from: "toby", name: "Toby", time: "6:22 PM", text: "MAYA" },
    { from: "toby", name: "Toby", time: "6:22 PM", text: "tell them" },
    { from: "maya", name: "Maya", time: "6:24 PM", text: "i don't watch one piece" },
    { from: "toby", name: "Toby", time: "6:24 PM", text: "you're dead to me" },
    { from: "maya", name: "Maya", time: "6:25 PM", text: "i've been dead to you for 6 months" },
    { from: "toby", name: "Toby", time: "6:25 PM", text: "and it still hurts" },
    { from: "samira", name: "Samira", time: "6:25 PM", text: "LMAO" },
    { from: "chloe", name: "Chloe", time: "6:26 PM", text: "anyway party. yes or no" },
    { from: "benji", name: "Benji", time: "6:26 PM", text: "yes" },
    { from: "samira", name: "Samira", time: "6:26 PM", text: "no" },
    { from: "chloe", name: "Chloe", time: "6:27 PM", text: "samira" },
    { from: "samira", name: "Samira", time: "6:27 PM", text: "chloe" },
    { from: "chloe", name: "Chloe", time: "6:27 PM", text: "fine. i'll go alone" },
    { from: "samira", name: "Samira", time: "6:27 PM", text: "you won't" },
    { from: "chloe", name: "Chloe", time: "6:28 PM", text: "i will" },
    { from: "samira", name: "Samira", time: "6:28 PM", text: "you won't" },
    { from: "chloe", name: "Chloe", time: "6:28 PM", text: "I WILL" },
    { from: "maya", name: "Maya", time: "6:29 PM", text: "you won't" },
    { from: "chloe", name: "Chloe", time: "6:29 PM", text: "ok maya why are you always right" },
    { from: "maya", name: "Maya", time: "6:30 PM", text: "because i'm always right" },
    { from: "chloe", name: "Chloe", time: "6:30 PM", text: "that's not how that works" },
    { from: "maya", name: "Maya", time: "6:30 PM", text: "it is" },
    { from: "toby", name: "Toby", time: "6:31 PM", text: "it kind of is" },
    { from: "chloe", name: "Chloe", time: "6:31 PM", text: "toby shut up" },
    { from: "toby", name: "Toby", time: "6:31 PM", text: "i'm just saying" },
    { from: "chloe", name: "Chloe", time: "6:31 PM", text: "SHUT UP" },
    { from: "toby", name: "Toby", time: "6:32 PM", text: "🙄" },

    { day: "Sunday 16 November" },
    { from: "chloe", name: "Chloe", time: "10:15 AM", text: "ok update" },
    { from: "chloe", name: "Chloe", time: "10:15 AM", text: "kyle texted me" },
    { from: "samira", name: "Samira", time: "10:16 AM", text: "and" },
    { from: "chloe", name: "Chloe", time: "10:16 AM", text: "and nothing" },
    { from: "chloe", name: "Chloe", time: "10:16 AM", text: "he just said \"hey\"" },
    { from: "samira", name: "Samira", time: "10:17 AM", text: "that's not nothing" },
    { from: "chloe", name: "Chloe", time: "10:17 AM", text: "it's nothing" },
    { from: "benji", name: "Benji", time: "10:18 AM", text: "it's something" },
    { from: "chloe", name: "Chloe", time: "10:18 AM", text: "benji you're the last person who should be commenting on this" },
    { from: "benji", name: "Benji", time: "10:18 AM", text: "why" },
    { from: "chloe", name: "Chloe", time: "10:19 AM", text: "because you've been in love with maya since year 8" },
    { from: "benji", name: "Benji", time: "10:19 AM", text: "I HAVE NOT" },
    { from: "samira", name: "Samira", time: "10:19 AM", text: "oh my god" },
    { from: "samira", name: "Samira", time: "10:19 AM", text: "CHLOE" },
    { from: "chloe", name: "Chloe", time: "10:19 AM", text: "what" },
    { from: "samira", name: "Samira", time: "10:20 AM", text: "you can't just say that" },
    { from: "chloe", name: "Chloe", time: "10:20 AM", text: "why not" },
    { from: "samira", name: "Samira", time: "10:20 AM", text: "because it's mean" },
    { from: "chloe", name: "Chloe", time: "10:21 AM", text: "it's true" },
    { from: "benji", name: "Benji", time: "10:21 AM", text: "it's not true" },
    { from: "chloe", name: "Chloe", time: "10:21 AM", text: "benji" },
    { from: "benji", name: "Benji", time: "10:21 AM", text: "IT'S NOT TRUE" },
    { from: "toby", name: "Toby", time: "10:22 AM", text: "this is better than one piece" },
    { from: "samira", name: "Samira", time: "10:22 AM", text: "toby" },
    { from: "toby", name: "Toby", time: "10:22 AM", text: "i said what i said" },
    { from: "maya", name: "Maya", time: "10:24 AM", text: "benji it's fine" },
    { from: "benji", name: "Benji", time: "10:24 AM", text: "it's not fine" },
    { from: "maya", name: "Maya", time: "10:25 AM", text: "it is" },
    { from: "benji", name: "Benji", time: "10:25 AM", text: "maya" },
    { from: "maya", name: "Maya", time: "10:25 AM", text: "benji" },
    { from: "benji", name: "Benji", time: "10:26 AM", text: "ugh" },
    { from: "chloe", name: "Chloe", time: "10:26 AM", text: "see" },
    { from: "samira", name: "Samira", time: "10:26 AM", text: "CHLOE" },
    { from: "chloe", name: "Chloe", time: "10:27 AM", text: "what" },
    { from: "maya", name: "Maya", time: "10:27 AM", text: "chloe stop" },
    { from: "chloe", name: "Chloe", time: "10:28 AM", text: "fine" },
    { from: "chloe", name: "Chloe", time: "10:28 AM", text: "sorry benji" },
    { from: "benji", name: "Benji", time: "10:29 AM", text: "whatever" },
    { from: "benji", name: "Benji", time: "10:29 AM", text: "i'm leaving the group" },
    { from: "samira", name: "Samira", time: "10:29 AM", text: "benji no" },
    { from: "benji", name: "Benji", time: "10:30 AM", text: "i'm serious" },
    { from: "samira", name: "Samira", time: "10:30 AM", text: "benji" },
    { from: "benji", name: "Benji", time: "10:30 AM", text: "goodbye" },
    { from: "benji", name: "Benji", time: "10:30 AM", text: "[left the group]" },
    { from: "samira", name: "Samira", time: "10:31 AM", text: "BENJI" },
    { from: "chloe", name: "Chloe", time: "10:31 AM", text: "he'll be back" },
    { from: "samira", name: "Samira", time: "10:31 AM", text: "chloe" },
    { from: "chloe", name: "Chloe", time: "10:31 AM", text: "he always comes back" },
    { from: "samira", name: "Samira", time: "10:32 AM", text: "because you keep doing this" },
    { from: "chloe", name: "Chloe", time: "10:32 AM", text: "i know" },
    { from: "samira", name: "Samira", time: "10:32 AM", text: "so stop" },
    { from: "chloe", name: "Chloe", time: "10:33 AM", text: "i can't help it" },
    { from: "chloe", name: "Chloe", time: "10:33 AM", text: "he's just so easy" },
    { from: "maya", name: "Maya", time: "10:34 AM", text: "that's not ok" },
    { from: "chloe", name: "Chloe", time: "10:35 AM", text: "i know" },
    { from: "chloe", name: "Chloe", time: "10:35 AM", text: "i'll apologise" },
    { from: "maya", name: "Maya", time: "10:36 AM", text: "you better" },
    { from: "chloe", name: "Chloe", time: "10:36 AM", text: "i will" },
    { from: "chloe", name: "Chloe", time: "10:37 AM", text: "[Benji was added by Chloe]" },
    { from: "chloe", name: "Chloe", time: "10:38 AM", text: "sorry benji" },
    { from: "benji", name: "Benji", time: "10:39 AM", text: "fine" },
    { from: "benji", name: "Benji", time: "10:39 AM", text: "but stop" },
    { from: "chloe", name: "Chloe", time: "10:39 AM", text: "i'll try" },
    { from: "benji", name: "Benji", time: "10:40 AM", text: "🙄" },
    { from: "maya", name: "Maya", time: "10:41 AM", text: "good" },

    { day: "Friday 21 November" },
    { from: "chloe", name: "Chloe", time: "4:30 PM", text: "OK WHO IS COMING TONIGHT" },
    { from: "samira", name: "Samira", time: "4:31 PM", text: "not me" },
    { from: "chloe", name: "Chloe", time: "4:31 PM", text: "samira" },
    { from: "samira", name: "Samira", time: "4:31 PM", text: "i have work" },
    { from: "chloe", name: "Chloe", time: "4:32 PM", text: "call in sick" },
    { from: "samira", name: "Samira", time: "4:32 PM", text: "i can't" },
    { from: "chloe", name: "Chloe", time: "4:32 PM", text: "you can" },
    { from: "samira", name: "Samira", time: "4:32 PM", text: "i can't" },
    { from: "chloe", name: "Chloe", time: "4:33 PM", text: "SAMIRA" },
    { from: "samira", name: "Samira", time: "4:33 PM", text: "CHLOE" },
    { from: "chloe", name: "Chloe", time: "4:33 PM", text: "fine" },
    { from: "chloe", name: "Chloe", time: "4:34 PM", text: "toby?" },
    { from: "toby", name: "Toby", time: "4:35 PM", text: "i'm watching one piece" },
    { from: "chloe", name: "Chloe", time: "4:35 PM", text: "you're always watching one piece" },
    { from: "toby", name: "Toby", time: "4:35 PM", text: "and?" },
    { from: "chloe", name: "Chloe", time: "4:36 PM", text: "and nothing. fine. benji?" },
    { from: "benji", name: "Benji", time: "4:37 PM", text: "i'll come" },
    { from: "chloe", name: "Chloe", time: "4:37 PM", text: "of course you will" },
    { from: "benji", name: "Benji", time: "4:37 PM", text: "what does that mean" },
    { from: "chloe", name: "Chloe", time: "4:37 PM", text: "nothing" },
    { from: "benji", name: "Benji", time: "4:38 PM", text: "chloe" },
    { from: "chloe", name: "Chloe", time: "4:38 PM", text: "benji" },
    { from: "benji", name: "Benji", time: "4:38 PM", text: "🙄" },
    { from: "chloe", name: "Chloe", time: "4:39 PM", text: "maya?" },
    { from: "maya", name: "Maya", time: "4:40 PM", text: "no" },
    { from: "chloe", name: "Chloe", time: "4:40 PM", text: "why not" },
    { from: "maya", name: "Maya", time: "4:40 PM", text: "not my thing" },
    { from: "chloe", name: "Chloe", time: "4:41 PM", text: "you never come to anything" },
    { from: "maya", name: "Maya", time: "4:41 PM", text: "correct" },
    { from: "chloe", name: "Chloe", time: "4:41 PM", text: "MAYA" },
    { from: "maya", name: "Maya", time: "4:42 PM", text: "chloe" },
    { from: "chloe", name: "Chloe", time: "4:42 PM", text: "you're so boring" },
    { from: "maya", name: "Maya", time: "4:42 PM", text: "i've been called worse" },
    { from: "chloe", name: "Chloe", time: "4:43 PM", text: "by who" },
    { from: "maya", name: "Maya", time: "4:43 PM", text: "you" },
    { from: "chloe", name: "Chloe", time: "4:43 PM", text: "fair" },
    { from: "samira", name: "Samira", time: "4:44 PM", text: "LMFAOOO" },
    { from: "chloe", name: "Chloe", time: "4:44 PM", text: "shut up samira" },
    { from: "samira", name: "Samira", time: "4:44 PM", text: "no" },
    { from: "chloe", name: "Chloe", time: "4:45 PM", text: "i'm going alone" },
    { from: "samira", name: "Samira", time: "4:45 PM", text: "you won't" },
    { from: "chloe", name: "Chloe", time: "4:45 PM", text: "I WILL" },
    { from: "samira", name: "Samira", time: "4:45 PM", text: "you won't" },
    { from: "chloe", name: "Chloe", time: "4:46 PM", text: "fine. benji's coming" },
    { from: "benji", name: "Benji", time: "4:46 PM", text: "i am?" },
    { from: "chloe", name: "Chloe", time: "4:47 PM", text: "you are" },
    { from: "benji", name: "Benji", time: "4:47 PM", text: "ok" },
    { from: "toby", name: "Toby", time: "4:48 PM", text: "have fun" },
    { from: "toby", name: "Toby", time: "4:48 PM", text: "i'll be here" },
    { from: "toby", name: "Toby", time: "4:48 PM", text: "watching peak fiction" },
    { from: "chloe", name: "Chloe", time: "4:49 PM", text: "toby no one cares" },
    { from: "toby", name: "Toby", time: "4:49 PM", text: "i care" },
    { from: "chloe", name: "Chloe", time: "4:49 PM", text: "that's sad" },
    { from: "toby", name: "Toby", time: "4:50 PM", text: "your face is sad" },
    { from: "chloe", name: "Chloe", time: "4:50 PM", text: "😐" },
    { from: "samira", name: "Samira", time: "4:51 PM", text: "💀" },
    { from: "maya", name: "Maya", time: "4:51 PM", text: "💀" },
    { from: "benji", name: "Benji", time: "4:51 PM", text: "💀" },
    { from: "toby", name: "Toby", time: "4:52 PM", text: "why is everyone bullying me" },
    { from: "samira", name: "Samira", time: "4:52 PM", text: "because you make it easy" },
    { from: "toby", name: "Toby", time: "4:52 PM", text: "🙄" },

    { day: "Saturday 22 November" },
    { from: "samira", name: "Samira", time: "1:20 PM", text: "ok so" },
    { from: "samira", name: "Samira", time: "1:20 PM", text: "i have news" },
    { from: "chloe", name: "Chloe", time: "1:21 PM", text: "what" },
    { from: "samira", name: "Samira", time: "1:21 PM", text: "there's a new guy at the kettle" },
    { from: "chloe", name: "Chloe", time: "1:22 PM", text: "ooooh" },
    { from: "samira", name: "Samira", time: "1:22 PM", text: "not like that" },
    { from: "chloe", name: "Chloe", time: "1:22 PM", text: "it's always like that with you" },
    { from: "samira", name: "Samira", time: "1:22 PM", text: "it's not" },
    { from: "chloe", name: "Chloe", time: "1:23 PM", text: "it is" },
    { from: "samira", name: "Samira", time: "1:23 PM", text: "CHLOE" },
    { from: "chloe", name: "Chloe", time: "1:23 PM", text: "SAMIRA" },
    { from: "samira", name: "Samira", time: "1:23 PM", text: "anyway he's like 40" },
    { from: "chloe", name: "Chloe", time: "1:24 PM", text: "oh" },
    { from: "samira", name: "Samira", time: "1:24 PM", text: "and he wears a grey coat" },
    { from: "samira", name: "Samira", time: "1:24 PM", text: "and he just sits there" },
    { from: "samira", name: "Samira", time: "1:24 PM", text: "and stares" },
    { from: "chloe", name: "Chloe", time: "1:25 PM", text: "stares at what" },
    { from: "samira", name: "Samira", time: "1:25 PM", text: "at the staff room door" },
    { from: "chloe", name: "Chloe", time: "1:25 PM", text: "that's weird" },
    { from: "samira", name: "Samira", time: "1:26 PM", text: "i know" },
    { from: "samira", name: "Samira", time: "1:26 PM", text: "maya" },
    { from: "samira", name: "Samira", time: "1:26 PM", text: "you're quiet" },
    { from: "maya", name: "Maya", time: "1:30 PM", text: "i'm here" },
    { from: "samira", name: "Samira", time: "1:30 PM", text: "you ok" },
    { from: "maya", name: "Maya", time: "1:31 PM", text: "yeah" },
    { from: "samira", name: "Samira", time: "1:31 PM", text: "you sure" },
    { from: "maya", name: "Maya", time: "1:32 PM", text: "yeah" },
    { from: "samira", name: "Samira", time: "1:32 PM", text: "ok" },
    { from: "chloe", name: "Chloe", time: "1:33 PM", text: "maya you've been weird lately" },
    { from: "maya", name: "Maya", time: "1:33 PM", text: "i haven't" },
    { from: "chloe", name: "Chloe", time: "1:34 PM", text: "you have" },
    { from: "benji", name: "Benji", time: "1:34 PM", text: "she has a bit" },
    { from: "maya", name: "Maya", time: "1:35 PM", text: "i haven't" },
    { from: "toby", name: "Toby", time: "1:35 PM", text: "you kind of have" },
    { from: "maya", name: "Maya", time: "1:36 PM", text: "toby you haven't spoken to me in 3 weeks" },
    { from: "toby", name: "Toby", time: "1:36 PM", text: "that doesn't mean i don't notice" },
    { from: "maya", name: "Maya", time: "1:36 PM", text: "🙄" },
    { from: "samira", name: "Samira", time: "1:37 PM", text: "she has a point" },
    { from: "chloe", name: "Chloe", time: "1:37 PM", text: "maya what's going on" },
    { from: "maya", name: "Maya", time: "1:38 PM", text: "nothing" },
    { from: "chloe", name: "Chloe", time: "1:38 PM", text: "maya" },
    { from: "maya", name: "Maya", time: "1:38 PM", text: "NOTHING" },
    { from: "samira", name: "Samira", time: "1:39 PM", text: "ok ok" },
    { from: "samira", name: "Samira", time: "1:39 PM", text: "let's drop it" },
    { from: "chloe", name: "Chloe", time: "1:39 PM", text: "fine" },
    { from: "benji", name: "Benji", time: "1:40 PM", text: "fine" },
    { from: "toby", name: "Toby", time: "1:40 PM", text: "fine" },
    { from: "maya", name: "Maya", time: "1:41 PM", text: "thanks" },

    { day: "Monday 24 November" },
    { from: "chloe", name: "Chloe", time: "11:00 AM", text: "ok so i have a theory" },
    { from: "chloe", name: "Chloe", time: "11:00 AM", text: "about the grey coat guy" },
    { from: "samira", name: "Samira", time: "11:01 AM", text: "chloe no" },
    { from: "chloe", name: "Chloe", time: "11:01 AM", text: "chloe yes" },
    { from: "samira", name: "Samira", time: "11:01 AM", text: "please no" },
    { from: "chloe", name: "Chloe", time: "11:02 AM", text: "he's a spy" },
    { from: "samira", name: "Samira", time: "11:02 AM", text: "he's not a spy" },
    { from: "chloe", name: "Chloe", time: "11:02 AM", text: "he IS" },
    { from: "samira", name: "Samira", time: "11:03 AM", text: "chloe" },
    { from: "chloe", name: "Chloe", time: "11:03 AM", text: "think about it" },
    { from: "chloe", name: "Chloe", time: "11:03 AM", text: "he comes in every day" },
    { from: "chloe", name: "Chloe", time: "11:04 AM", text: "doesn't order anything" },
    { from: "chloe", name: "Chloe", time: "11:04 AM", text: "just stares at the staff room" },
    { from: "chloe", name: "Chloe", time: "11:04 AM", text: "he's obviously a spy" },
    { from: "samira", name: "Samira", time: "11:05 AM", text: "a spy for WHO" },
    { from: "chloe", name: "Chloe", time: "11:05 AM", text: "i don't know yet" },
    { from: "chloe", name: "Chloe", time: "11:05 AM", text: "that's why it's a theory" },
    { from: "samira", name: "Samira", time: "11:06 AM", text: "💀" },
    { from: "toby", name: "Toby", time: "11:06 AM", text: "i think he's just weird" },
    { from: "chloe", name: "Chloe", time: "11:07 AM", text: "that's what a spy would want you to think" },
    { from: "toby", name: "Toby", time: "11:07 AM", text: "no it's not" },
    { from: "chloe", name: "Chloe", time: "11:07 AM", text: "it is" },
    { from: "toby", name: "Toby", time: "11:08 AM", text: "🙄" },
    { from: "benji", name: "Benji", time: "11:08 AM", text: "has anyone told the manager" },
    { from: "samira", name: "Samira", time: "11:09 AM", text: "i did" },
    { from: "samira", name: "Samira", time: "11:09 AM", text: "he said he'll keep an eye out" },
    { from: "chloe", name: "Chloe", time: "11:09 AM", text: "he won't" },
    { from: "samira", name: "Samira", time: "11:10 AM", text: "he will" },
    { from: "chloe", name: "Chloe", time: "11:10 AM", text: "he WON'T" },
    { from: "samira", name: "Samira", time: "11:10 AM", text: "CHLOE" },
    { from: "chloe", name: "Chloe", time: "11:10 AM", text: "SAMIRA" },
    { from: "maya", name: "Maya", time: "11:12 AM", text: "he won't" },
    { from: "samira", name: "Samira", time: "11:12 AM", text: "maya" },
    { from: "maya", name: "Maya", time: "11:12 AM", text: "what" },
    { from: "samira", name: "Samira", time: "11:13 AM", text: "don't encourage her" },
    { from: "maya", name: "Maya", time: "11:13 AM", text: "i'm not" },
    { from: "maya", name: "Maya", time: "11:13 AM", text: "i'm just agreeing" },
    { from: "samira", name: "Samira", time: "11:14 AM", text: "😭" },
    { from: "toby", name: "Toby", time: "11:14 AM", text: "LMAOOO" },
    { from: "chloe", name: "Chloe", time: "11:15 AM", text: "see maya agrees" },
    { from: "samira", name: "Samira", time: "11:15 AM", text: "she doesn't" },
    { from: "chloe", name: "Chloe", time: "11:15 AM", text: "she does" },
    { from: "samira", name: "Samira", time: "11:15 AM", text: "maya tell her" },
    { from: "maya", name: "Maya", time: "11:17 AM", text: "i don't want to be involved" },
    { from: "samira", name: "Samira", time: "11:17 AM", text: "MAYA" },
    { from: "maya", name: "Maya", time: "11:18 AM", text: "😐" },
    { from: "samira", name: "Samira", time: "11:18 AM", text: "fine" },
    { from: "samira", name: "Samira", time: "11:19 AM", text: "i hate all of you" },
    { from: "chloe", name: "Chloe", time: "11:19 AM", text: "you love us" },
    { from: "samira", name: "Samira", time: "11:19 AM", text: "i tolerate you" },
    { from: "chloe", name: "Chloe", time: "11:20 AM", text: "same thing" },
    { from: "samira", name: "Samira", time: "11:20 AM", text: "it's not" },
    { from: "chloe", name: "Chloe", time: "11:20 AM", text: "it is" },

    { day: "Tuesday 25 November" },
    { from: "chloe", name: "Chloe", time: "8:00 AM", text: "ok heading to benji's" },
    { from: "chloe", name: "Chloe", time: "8:00 AM", text: "this is going to be boring" },
    { from: "benji", name: "Benji", time: "8:01 AM", text: "thanks" },
    { from: "chloe", name: "Chloe", time: "8:01 AM", text: "you're welcome" },
    { from: "toby", name: "Toby", time: "8:05 AM", text: "have fun" },
    { from: "toby", name: "Toby", time: "8:05 AM", text: "i'll be watching peak" },
    { from: "chloe", name: "Chloe", time: "8:06 AM", text: "we know" },
    { from: "samira", name: "Samira", time: "8:15 AM", text: "maya are you coming to the kettle later" },
    { from: "samira", name: "Samira", time: "8:30 AM", text: "maya" },
    { from: "samira", name: "Samira", time: "8:45 AM", text: "maya" },
    { from: "samira", name: "Samira", time: "8:46 AM", text: "she's not replying" },
    { from: "chloe", name: "Chloe", time: "8:47 AM", text: "she's probably studying" },
    { from: "samira", name: "Samira", time: "8:47 AM", text: "yeah probably" },
    { from: "samira", name: "Samira", time: "8:48 AM", text: "ok well i'm at work if anyone needs me" },
    { from: "chloe", name: "Chloe", time: "8:49 AM", text: "👍" },
    { from: "benji", name: "Benji", time: "8:49 AM", text: "👍" },
    { from: "toby", name: "Toby", time: "8:49 AM", text: "👍" },

    { day: "Wednesday 26 November" },
    { from: "samira", name: "Samira", time: "10:15 AM", text: "has anyone heard from maya" },
    { from: "chloe", name: "Chloe", time: "10:20 AM", text: "no" },
    { from: "benji", name: "Benji", time: "10:21 AM", text: "no" },
    { from: "toby", name: "Toby", time: "10:22 AM", text: "no" },
    { from: "samira", name: "Samira", time: "10:23 AM", text: "she hasn't been online since tuesday" },
    { from: "chloe", name: "Chloe", time: "10:24 AM", text: "she does that sometimes" },
    { from: "samira", name: "Samira", time: "10:24 AM", text: "not like this" },
    { from: "chloe", name: "Chloe", time: "10:25 AM", text: "she does" },
    { from: "samira", name: "Samira", time: "10:25 AM", text: "chloe" },
    { from: "chloe", name: "Chloe", time: "10:25 AM", text: "what" },
    { from: "samira", name: "Samira", time: "10:26 AM", text: "something's wrong" },
    { from: "chloe", name: "Chloe", time: "10:26 AM", text: "nothing's wrong" },
    { from: "samira", name: "Samira", time: "10:26 AM", text: "CHLOE" },
    { from: "chloe", name: "Chloe", time: "10:27 AM", text: "SAMIRA" },
    { from: "samira", name: "Samira", time: "10:27 AM", text: "i'm serious" },
    { from: "chloe", name: "Chloe", time: "10:28 AM", text: "ok ok" },
    { from: "chloe", name: "Chloe", time: "10:28 AM", text: "but what can we do" },
    { from: "samira", name: "Samira", time: "10:29 AM", text: "i don't know" },
    { from: "samira", name: "Samira", time: "10:29 AM", text: "i'm going to text her mum" },
    { from: "chloe", name: "Chloe", time: "10:30 AM", text: "do that" },
    { from: "toby", name: "Toby", time: "10:31 AM", text: "keep us updated" },
    { from: "samira", name: "Samira", time: "10:31 AM", text: "i will" },

    { day: "Thursday 27 November" },
    { from: "samira", name: "Samira", time: "4:15 PM", text: "guys" },
    { from: "samira", name: "Samira", time: "4:15 PM", text: "maya's missing" },
    { from: "chloe", name: "Chloe", time: "4:16 PM", text: "WHAT" },
    { from: "benji", name: "Benji", time: "4:16 PM", text: "what" },
    { from: "toby", name: "Toby", time: "4:16 PM", text: "WHAT" },
    { from: "samira", name: "Samira", time: "4:17 PM", text: "her mum called the police" },
    { from: "samira", name: "Samira", time: "4:17 PM", text: "she hasn't been home since tuesday" },
    { from: "chloe", name: "Chloe", time: "4:18 PM", text: "oh my god" },
    { from: "benji", name: "Benji", time: "4:18 PM", text: "oh my god" },
    { from: "toby", name: "Toby", time: "4:18 PM", text: "oh my god" },
    { from: "samira", name: "Samira", time: "4:19 PM", text: "i'm freaking out" },
    { from: "chloe", name: "Chloe", time: "4:19 PM", text: "me too" },
    { from: "benji", name: "Benji", time: "4:19 PM", text: "me too" },
    { from: "toby", name: "Toby", time: "4:20 PM", text: "me too" },
    { from: "samira", name: "Samira", time: "4:20 PM", text: "stop saying me too" },
    { from: "chloe", name: "Chloe", time: "4:21 PM", text: "sorry" },
    { from: "benji", name: "Benji", time: "4:21 PM", text: "sorry" },
    { from: "toby", name: "Toby", time: "4:21 PM", text: "sorry" },
    { from: "samira", name: "Samira", time: "4:22 PM", text: "i'm going to her house" },
    { from: "chloe", name: "Chloe", time: "4:22 PM", text: "do you want company" },
    { from: "samira", name: "Samira", time: "4:23 PM", text: "no" },
    { from: "samira", name: "Samira", time: "4:23 PM", text: "i need to be alone" },
    { from: "chloe", name: "Chloe", time: "4:23 PM", text: "ok" },
    { from: "chloe", name: "Chloe", time: "4:24 PM", text: "text us" },
    { from: "samira", name: "Samira", time: "4:24 PM", text: "i will" },

    { day: "Friday 28 November" },
    { from: "chloe", name: "Chloe", time: "8:30 AM", text: "samira" },
    { from: "chloe", name: "Chloe", time: "8:30 AM", text: "samira" },
    { from: "chloe", name: "Chloe", time: "8:30 AM", text: "SAMIRA" },
    { from: "chloe", name: "Chloe", time: "8:31 AM", text: "did you find anything" },
    { from: "chloe", name: "Chloe", time: "8:31 AM", text: "samira" },
    { from: "chloe", name: "Chloe", time: "8:32 AM", text: "please" },
    { from: "chloe", name: "Chloe", time: "8:32 AM", text: "i'm worried about you too" },
    { from: "chloe", name: "Chloe", time: "8:33 AM", text: "please text back" },
    { from: "chloe", name: "Chloe", time: "8:33 AM", text: "please" },
    { from: "benji", name: "Benji", time: "9:15 AM", text: "samira" },
    { from: "benji", name: "Benji", time: "9:15 AM", text: "please" },
    { from: "toby", name: "Toby", time: "9:20 AM", text: "samira please" },
    { from: "toby", name: "Toby", time: "9:20 AM", text: "we're all scared" },
    { from: "toby", name: "Toby", time: "9:21 AM", text: "please just tell us you're ok" },
    { from: "chloe", name: "Chloe", time: "10:00 AM", text: "samira" },
    { from: "chloe", name: "Chloe", time: "10:00 AM", text: "please" },
    { from: "chloe", name: "Chloe", time: "10:00 AM", text: "please" },
    { from: "chloe", name: "Chloe", time: "10:01 AM", text: "please" },
    { from: "chloe", name: "Chloe", time: "10:01 AM", text: "🙏" },
    { from: "benji", name: "Benji", time: "10:02 AM", text: "🙏" },
    { from: "toby", name: "Toby", time: "10:02 AM", text: "🙏" },
    { from: "toby", name: "Toby", time: "11:00 AM", text: "did anyone hear anything" },
    { from: "chloe", name: "Chloe", time: "11:02 AM", text: "no" },
    { from: "benji", name: "Benji", time: "11:02 AM", text: "no" },
    { from: "toby", name: "Toby", time: "11:03 AM", text: "i can't do this" },
    { from: "toby", name: "Toby", time: "11:03 AM", text: "i can't just sit here" },
    { from: "chloe", name: "Chloe", time: "11:04 AM", text: "none of us can" },
    { from: "chloe", name: "Chloe", time: "11:04 AM", text: "but what else do we do" },
    { from: "benji", name: "Benji", time: "11:05 AM", text: "we wait" },
    { from: "benji", name: "Benji", time: "11:05 AM", text: "we just wait" },
    { from: "toby", name: "Toby", time: "11:06 AM", text: "i hate waiting" },
    { from: "chloe", name: "Chloe", time: "11:06 AM", text: "same" },
    { from: "chloe", name: "Chloe", time: "11:06 AM", text: "omg wait who said that" },
    { from: "chloe", name: "Chloe", time: "11:07 AM", text: "sorry" },
    { from: "chloe", name: "Chloe", time: "11:07 AM", text: "wrong chat" },
    { from: "toby", name: "Toby", time: "11:08 AM", text: "chloe" },
    { from: "chloe", name: "Chloe", time: "11:08 AM", text: "i know" },
    { from: "chloe", name: "Chloe", time: "11:08 AM", text: "sorry" },
    { from: "benji", name: "Benji", time: "11:09 AM", text: "does anyone know if samira's ok" },
    { from: "chloe", name: "Chloe", time: "11:10 AM", text: "no" },
    { from: "chloe", name: "Chloe", time: "11:10 AM", text: "she hasn't replied since yesterday" },
    { from: "toby", name: "Toby", time: "11:11 AM", text: "should we go to the kettle" },
    { from: "chloe", name: "Chloe", time: "11:12 AM", text: "i already did" },
    { from: "chloe", name: "Chloe", time: "11:12 AM", text: "she wasn't there" },
    { from: "chloe", name: "Chloe", time: "11:12 AM", text: "no one knew where she was" },
    { from: "benji", name: "Benji", time: "11:13 AM", text: "this is bad" },
    { from: "chloe", name: "Chloe", time: "11:13 AM", text: "i know" },
    { from: "toby", name: "Toby", time: "11:14 AM", text: "we should call the police" },
    { from: "chloe", name: "Chloe", time: "11:14 AM", text: "her mum already did" },
    { from: "toby", name: "Toby", time: "11:14 AM", text: "for maya" },
    { from: "toby", name: "Toby", time: "11:15 AM", text: "i mean for samira" },
    { from: "chloe", name: "Chloe", time: "11:15 AM", text: "she's not missing" },
    { from: "chloe", name: "Chloe", time: "11:15 AM", text: "she's just not replying" },
    { from: "benji", name: "Benji", time: "11:16 AM", text: "that's what maya did" },
    { from: "chloe", name: "Chloe", time: "11:16 AM", text: "..." },
    { from: "chloe", name: "Chloe", time: "11:16 AM", text: "don't say that" },
    { from: "toby", name: "Toby", time: "11:17 AM", text: "he's right though" },
    { from: "chloe", name: "Chloe", time: "11:17 AM", text: "toby" },
    { from: "toby", name: "Toby", time: "11:17 AM", text: "sorry" },
    { from: "chloe", name: "Chloe", time: "11:18 AM", text: "we wait" },
    { from: "chloe", name: "Chloe", time: "11:18 AM", text: "that's all we do" },
    { from: "chloe", name: "Chloe", time: "11:18 AM", text: "we wait" },
    { from: "benji", name: "Benji", time: "11:19 AM", text: "🙏" },
    { from: "toby", name: "Toby", time: "11:19 AM", text: "🙏" }
  ]
};
