/* =========================================================
   CHAT: Dad
   ========================================================= */

window.CHATS_DATA.dad = {
  name: "Dad",
  bio: "written lightly, remembered heavily",
  avatarInitials: "D",
  avatarColor: "#4a5a6a",
  preview: "I transferred the money for the winter coat. Buy a warm one.",
  time: "Mon",
  unreadCount: 0,
  messages: [
    { day: "Sunday 2 March" },
    { from: "dad", time: "10:14 AM", text: "Maya" },
    { from: "dad", time: "10:14 AM", text: "I transferred £100 to your account" },
    { from: "dad", time: "10:14 AM", text: "For the school trip" },
    { from: "dad", time: "10:15 AM", text: "Your mum mentioned it" },
    { from: "maya", time: "10:20 AM", text: "thanks" },
    { from: "dad", time: "10:20 AM", text: "You're welcome" },
    { from: "dad", time: "10:21 AM", text: "Do you need anything else?" },
    { from: "maya", time: "10:25 AM", text: "no" },
    { from: "dad", time: "10:25 AM", text: "Okay" },
    { from: "dad", time: "10:26 AM", text: "Let me know if you do" },

    { day: "Saturday 12 April" },
    { from: "dad", time: "3:40 PM", text: "Maya" },
    { from: "dad", time: "3:40 PM", text: "Did you get my last transfer?" },
    { from: "maya", time: "3:45 PM", text: "yes" },
    { from: "dad", time: "3:45 PM", text: "Good" },
    { from: "dad", time: "3:46 PM", text: "I can send more if you need" },
    { from: "maya", time: "3:50 PM", text: "I'm fine" },
    { from: "dad", time: "3:50 PM", text: "Okay" },
    { from: "dad", time: "3:51 PM", text: "Just checking" },

    { day: "Sunday 4 May" },
    { from: "dad", time: "11:20 AM", text: "Maya" },
    { from: "dad", time: "11:20 AM", text: "I saw a coat in a shop window" },
    { from: "dad", time: "11:21 AM", text: "Thought of you" },
    { from: "dad", time: "11:21 AM", text: "It was green" },
    { from: "dad", time: "11:21 AM", text: "You used to like green" },
    { from: "maya", time: "11:30 AM", text: "I don't anymore" },
    { from: "dad", time: "11:30 AM", text: "Oh" },
    { from: "dad", time: "11:31 AM", text: "Okay" },
    { from: "dad", time: "11:31 AM", text: "What colours do you like now?" },
    { from: "maya", time: "11:35 AM", text: "doesn't matter" },
    { from: "dad", time: "11:35 AM", text: "It matters to me" },
    { from: "maya", time: "11:36 AM", text: "🙄" },
    { from: "dad", time: "11:36 AM", text: "Fair" },

    { day: "Tuesday 6 May" },
    { from: "dad", time: "8:02 AM", text: "Maya" },
    { from: "dad", time: "8:02 AM", text: "I transferred £60" },
    { from: "dad", time: "8:02 AM", text: "For whatever you need" },
    { from: "maya", time: "8:15 AM", text: "why" },
    { from: "dad", time: "8:15 AM", text: "Because I can" },
    { from: "maya", time: "8:16 AM", text: "ok" },
    { from: "dad", time: "8:16 AM", text: "thanks" },
    { from: "dad", time: "8:17 AM", text: "No, thank you" },
    { from: "maya", time: "8:18 AM", text: "for what" },
    { from: "dad", time: "8:18 AM", text: "For accepting it" },
    { from: "maya", time: "8:20 AM", text: "..." },
    { from: "maya", time: "8:21 AM", text: "thanks" },

    { day: "Sunday 8 June" },
    { from: "dad", time: "2:30 PM", text: "Maya" },
    { from: "dad", time: "2:30 PM", text: "Are you okay for money?" },
    { from: "maya", time: "2:45 PM", text: "yes" },
    { from: "dad", time: "2:45 PM", text: "Are you sure?" },
    { from: "maya", time: "2:46 PM", text: "yes" },
    { from: "dad", time: "2:46 PM", text: "Because I can send more" },
    { from: "maya", time: "2:47 PM", text: "I'm fine" },
    { from: "dad", time: "2:47 PM", text: "Okay" },
    { from: "dad", time: "2:48 PM", text: "Just checking" },

    { day: "Saturday 21 June" },
    { from: "dad", time: "9:00 AM", text: "Maya" },
    { from: "dad", time: "9:00 AM", text: "I know I'm late" },
    { from: "dad", time: "9:00 AM", text: "Happy birthday for last month" },
    { from: "dad", time: "9:01 AM", text: "I'm sorry I missed it" },
    { from: "dad", time: "9:01 AM", text: "I transferred £200" },
    { from: "dad", time: "9:02 AM", text: "Buy yourself something nice" },
    { from: "maya", time: "9:30 AM", text: "thanks" },
    { from: "dad", time: "9:30 AM", text: "You're welcome" },
    { from: "dad", time: "9:31 AM", text: "I love you" },
    { from: "maya", time: "9:40 AM", text: "👍" },

    { day: "Saturday 28 June" },
    { from: "dad", time: "10:15 AM", text: "Maya" },
    { from: "dad", time: "10:15 AM", text: "Did the money come through?" },
    { from: "maya", time: "10:25 AM", text: "yes" },
    { from: "dad", time: "10:25 AM", text: "Good" },
    { from: "dad", time: "10:26 AM", text: "Buy something nice" },
    { from: "maya", time: "10:30 AM", text: "I will" },
    { from: "dad", time: "10:30 AM", text: "What are you going to buy?" },
    { from: "maya", time: "10:32 AM", text: "stuff" },
    { from: "dad", time: "10:32 AM", text: "What stuff?" },
    { from: "maya", time: "10:33 AM", text: "just stuff" },
    { from: "dad", time: "10:33 AM", text: "Okay" },
    { from: "dad", time: "10:34 AM", text: "I'm just curious" },
    { from: "maya", time: "10:35 AM", text: "I know" },
    { from: "dad", time: "10:35 AM", text: "Okay" },

    { day: "Sunday 13 July" },
    { from: "maya", time: "4:20 PM", text: "dad" },
    { from: "dad", time: "4:20 PM", text: "Maya?" },
    { from: "dad", time: "4:20 PM", text: "Is everything okay?" },
    { from: "maya", time: "4:22 PM", text: "can you send me money" },
    { from: "dad", time: "4:22 PM", text: "Of course" },
    { from: "dad", time: "4:22 PM", text: "How much?" },
    { from: "maya", time: "4:23 PM", text: "50" },
    { from: "dad", time: "4:23 PM", text: "Done" },
    { from: "dad", time: "4:23 PM", text: "Sent" },
    { from: "dad", time: "4:24 PM", text: "Is everything okay?" },
    { from: "maya", time: "4:25 PM", text: "yes" },
    { from: "dad", time: "4:25 PM", text: "Are you sure?" },
    { from: "maya", time: "4:26 PM", text: "yes" },
    { from: "dad", time: "4:26 PM", text: "Okay" },
    { from: "dad", time: "4:27 PM", text: "Let me know if you need more" },
    { from: "maya", time: "4:30 PM", text: "thanks" },
    { from: "dad", time: "4:30 PM", text: "You're welcome" },
    { from: "dad", time: "4:31 PM", text: "I love you" },
    { from: "maya", time: "4:35 PM", text: "👍" },

    { day: "Sunday 20 July" },
    { from: "maya", time: "1:10 PM", text: "dad" },
    { from: "dad", time: "1:10 PM", text: "Yes?" },
    { from: "maya", time: "1:11 PM", text: "I need money" },
    { from: "dad", time: "1:11 PM", text: "How much?" },
    { from: "maya", time: "1:11 PM", text: "80" },
    { from: "dad", time: "1:12 PM", text: "Done" },
    { from: "dad", time: "1:12 PM", text: "Sent" },
    { from: "dad", time: "1:12 PM", text: "For what, if you don't mind me asking" },
    { from: "maya", time: "1:15 PM", text: "school stuff" },
    { from: "dad", time: "1:15 PM", text: "Okay" },
    { from: "dad", time: "1:16 PM", text: "Let me know if you need more" },
    { from: "maya", time: "1:18 PM", text: "thanks" },
    { from: "dad", time: "1:18 PM", text: "You're welcome" },

    { day: "Saturday 2 August" },
    { from: "maya", time: "11:40 AM", text: "dad" },
    { from: "dad", time: "11:40 AM", text: "Yes?" },
    { from: "maya", time: "11:41 AM", text: "I need money" },
    { from: "dad", time: "11:41 AM", text: "How much?" },
    { from: "maya", time: "11:42 AM", text: "120" },
    { from: "dad", time: "11:42 AM", text: "Done" },
    { from: "dad", time: "11:42 AM", text: "Sent" },
    { from: "dad", time: "11:43 AM", text: "Maya" },
    { from: "maya", time: "11:45 AM", text: "yes" },
    { from: "dad", time: "11:45 AM", text: "Are you okay?" },
    { from: "maya", time: "11:46 AM", text: "yes" },
    { from: "dad", time: "11:46 AM", text: "You've been asking for money a lot lately" },
    { from: "maya", time: "11:47 AM", text: "is that a problem" },
    { from: "dad", time: "11:47 AM", text: "No" },
    { from: "dad", time: "11:47 AM", text: "Never" },
    { from: "dad", time: "11:48 AM", text: "I just want to make sure you're okay" },
    { from: "maya", time: "11:49 AM", text: "I'm fine" },
    { from: "dad", time: "11:49 AM", text: "Okay" },
    { from: "dad", time: "11:50 AM", text: "I love you" },
    { from: "maya", time: "11:52 AM", text: "thanks" },

    { day: "Sunday 10 August" },
    { from: "dad", time: "5:30 PM", text: "Maya" },
    { from: "dad", time: "5:30 PM", text: "Did you get the transfer?" },
    { from: "maya", time: "5:45 PM", text: "yes" },
    { from: "dad", time: "5:45 PM", text: "Good" },
    { from: "dad", time: "5:46 PM", text: "I can send more" },
    { from: "maya", time: "5:47 PM", text: "I'm okay" },
    { from: "dad", time: "5:47 PM", text: "Are you sure?" },
    { from: "maya", time: "5:48 PM", text: "yes" },
    { from: "dad", time: "5:48 PM", text: "Okay" },
    { from: "dad", time: "5:49 PM", text: "Just checking" },

    { day: "Saturday 23 August" },
    { from: "maya", time: "3:20 PM", text: "dad" },
    { from: "dad", time: "3:20 PM", text: "Yes?" },
    { from: "maya", time: "3:21 PM", text: "can you send me money" },
    { from: "dad", time: "3:21 PM", text: "Of course" },
    { from: "dad", time: "3:21 PM", text: "How much?" },
    { from: "maya", time: "3:22 PM", text: "60" },
    { from: "dad", time: "3:22 PM", text: "Done" },
    { from: "dad", time: "3:22 PM", text: "Sent" },
    { from: "dad", time: "3:23 PM", text: "Maya" },
    { from: "maya", time: "3:25 PM", text: "yes" },
    { from: "dad", time: "3:25 PM", text: "Can I call you?" },
    { from: "maya", time: "3:26 PM", text: "no" },
    { from: "dad", time: "3:26 PM", text: "Okay" },
    { from: "dad", time: "3:27 PM", text: "Just checking" },
    { from: "maya", time: "3:28 PM", text: "thanks for the money" },
    { from: "dad", time: "3:28 PM", text: "You're welcome" },
    { from: "dad", time: "3:28 PM", text: "Always" },

    { day: "Sunday 7 September" },
    { from: "maya", time: "8:15 AM", text: "dad" },
    { from: "dad", time: "8:15 AM", text: "Yes?" },
    { from: "maya", time: "8:16 AM", text: "I need money" },
    { from: "dad", time: "8:16 AM", text: "How much?" },
    { from: "maya", time: "8:17 AM", text: "45" },
    { from: "dad", time: "8:17 AM", text: "Done" },
    { from: "dad", time: "8:17 AM", text: "Sent" },
    { from: "dad", time: "8:18 AM", text: "Maya" },
    { from: "maya", time: "8:20 AM", text: "yes" },
    { from: "dad", time: "8:20 AM", text: "Is everything okay at school?" },
    { from: "maya", time: "8:21 AM", text: "yes" },
    { from: "dad", time: "8:21 AM", text: "And at home?" },
    { from: "maya", time: "8:22 AM", text: "yes" },
    { from: "dad", time: "8:22 AM", text: "Okay" },
    { from: "dad", time: "8:23 AM", text: "Let me know if you need more" },
    { from: "maya", time: "8:25 AM", text: "thanks" },

    { day: "Saturday 20 September" },
    { from: "dad", time: "7:30 PM", text: "Maya" },
    { from: "dad", time: "7:30 PM", text: "Big day tomorrow" },
    { from: "dad", time: "7:31 PM", text: "17" },
    { from: "dad", time: "7:31 PM", text: "That's a proper age" },
    { from: "maya", time: "7:45 PM", text: "it's just a number" },
    { from: "dad", time: "7:45 PM", text: "It's a big number" },
    { from: "maya", time: "7:46 PM", text: "it's not" },
    { from: "dad", time: "7:46 PM", text: "It is" },
    { from: "dad", time: "7:47 PM", text: "I transferred £250" },
    { from: "dad", time: "7:47 PM", text: "Buy yourself something nice" },
    { from: "maya", time: "7:50 PM", text: "thanks" },
    { from: "dad", time: "7:50 PM", text: "You're welcome" },
    { from: "dad", time: "7:51 PM", text: "I love you" },
    { from: "maya", time: "7:55 PM", text: "👍" },

    { day: "Sunday 21 September" },
    { from: "dad", time: "9:00 AM", text: "Happy Birthday Maya" },
    { from: "dad", time: "9:00 AM", text: "I hope you have a good day" },
    { from: "dad", time: "9:01 AM", text: "I'm sorry I can't be there" },
    { from: "dad", time: "9:01 AM", text: "I tried to get the day off" },
    { from: "dad", time: "9:02 AM", text: "But work is work" },
    { from: "maya", time: "9:30 AM", text: "it's fine" },
    { from: "dad", time: "9:30 AM", text: "It's not fine" },
    { from: "maya", time: "9:31 AM", text: "it is" },
    { from: "dad", time: "9:31 AM", text: "It's not" },
    { from: "maya", time: "9:32 AM", text: "it is" },
    { from: "dad", time: "9:32 AM", text: "Maya" },
    { from: "maya", time: "9:33 AM", text: "dad" },
    { from: "dad", time: "9:33 AM", text: "I'm sorry" },
    { from: "maya", time: "9:34 AM", text: "I know" },
    { from: "dad", time: "9:34 AM", text: "I love you" },
    { from: "maya", time: "9:35 AM", text: "I know" },
    { from: "dad", time: "9:35 AM", text: "Do you love me?" },
    { from: "maya", time: "9:40 AM", text: "..." },
    { from: "dad", time: "9:40 AM", text: "You don't have to answer that" },
    { from: "maya", time: "9:42 AM", text: "I don't know" },
    { from: "dad", time: "9:42 AM", text: "That's okay" },
    { from: "dad", time: "9:43 AM", text: "That's an honest answer" },
    { from: "maya", time: "9:44 AM", text: "yeah" },
    { from: "dad", time: "9:44 AM", text: "I'll take it" },
    { from: "maya", time: "9:45 AM", text: "ok" },
    { from: "dad", time: "9:45 AM", text: "Did you get the gift?" },
    { from: "maya", time: "9:50 AM", text: "yes" },
    { from: "dad", time: "9:50 AM", text: "Do you like it?" },
    { from: "maya", time: "9:52 AM", text: "it's fine" },
    { from: "dad", time: "9:52 AM", text: "Just fine?" },
    { from: "maya", time: "9:53 AM", text: "it's a necklace" },
    { from: "dad", time: "9:53 AM", text: "It's a locket" },
    { from: "maya", time: "9:54 AM", text: "same thing" },
    { from: "dad", time: "9:54 AM", text: "It's not" },
    { from: "dad", time: "9:55 AM", text: "It's a locket" },
    { from: "dad", time: "9:55 AM", text: "You can put a picture in it" },
    { from: "maya", time: "9:56 AM", text: "of who" },
    { from: "dad", time: "9:56 AM", text: "Anyone" },
    { from: "dad", time: "9:57 AM", text: "Me?" },
    { from: "maya", time: "9:58 AM", text: "why would I put a picture of you in it" },
    { from: "dad", time: "9:58 AM", text: "Because I'm your dad" },
    { from: "maya", time: "9:59 AM", text: "🙄" },
    { from: "dad", time: "9:59 AM", text: "Fair" },
    { from: "dad", time: "10:00 AM", text: "Okay" },
    { from: "dad", time: "10:00 AM", text: "Put whoever you want" },
    { from: "maya", time: "10:02 AM", text: "I will" },
    { from: "dad", time: "10:02 AM", text: "Good" },
    { from: "dad", time: "10:03 AM", text: "I love you" },
    { from: "maya", time: "10:05 AM", text: "thanks" },
    { from: "dad", time: "10:06 AM", text: "Goodnight Maya" },
    { from: "maya", time: "10:07 AM", text: "goodnight" },

    { day: "Saturday 4 October" },
    { from: "maya", time: "2:15 PM", text: "dad" },
    { from: "dad", time: "2:15 PM", text: "Yes?" },
    { from: "maya", time: "2:16 PM", text: "I need money" },
    { from: "dad", time: "2:16 PM", text: "How much?" },
    { from: "maya", time: "2:17 PM", text: "90" },
    { from: "dad", time: "2:17 PM", text: "Done" },
    { from: "dad", time: "2:17 PM", text: "Sent" },
    { from: "dad", time: "2:18 PM", text: "Maya" },
    { from: "maya", time: "2:20 PM", text: "yes" },
    { from: "dad", time: "2:20 PM", text: "Are you sure everything is okay?" },
    { from: "maya", time: "2:21 PM", text: "yes" },
    { from: "dad", time: "2:21 PM", text: "You've been asking for money a lot" },
    { from: "maya", time: "2:22 PM", text: "is that a problem" },
    { from: "dad", time: "2:22 PM", text: "No" },
    { from: "dad", time: "2:22 PM", text: "Never" },
    { from: "dad", time: "2:23 PM", text: "I'm glad you ask" },
    { from: "maya", time: "2:24 PM", text: "why" },
    { from: "dad", time: "2:24 PM", text: "Because it means you're talking to me" },
    { from: "maya", time: "2:26 PM", text: "..." },
    { from: "maya", time: "2:27 PM", text: "ok" },
    { from: "dad", time: "2:27 PM", text: "I love you" },
    { from: "maya", time: "2:29 PM", text: "thanks" },

    { day: "Sunday 12 October" },
    { from: "maya", time: "6:30 PM", text: "dad" },
    { from: "dad", time: "6:30 PM", text: "Yes?" },
    { from: "maya", time: "6:31 PM", text: "can you send me money" },
    { from: "dad", time: "6:31 PM", text: "Of course" },
    { from: "dad", time: "6:31 PM", text: "How much?" },
    { from: "maya", time: "6:32 PM", text: "70" },
    { from: "dad", time: "6:32 PM", text: "Done" },
    { from: "dad", time: "6:32 PM", text: "Sent" },
    { from: "dad", time: "6:33 PM", text: "Maya" },
    { from: "maya", time: "6:35 PM", text: "yes" },
    { from: "dad", time: "6:35 PM", text: "Can I see you?" },
    { from: "maya", time: "6:36 PM", text: "no" },
    { from: "dad", time: "6:36 PM", text: "Why not?" },
    { from: "maya", time: "6:37 PM", text: "busy" },
    { from: "dad", time: "6:37 PM", text: "With what?" },
    { from: "maya", time: "6:38 PM", text: "things" },
    { from: "dad", time: "6:38 PM", text: "Maya" },
    { from: "maya", time: "6:39 PM", text: "dad" },
    { from: "dad", time: "6:39 PM", text: "Fine" },
    { from: "dad", time: "6:40 PM", text: "But I'm here" },
    { from: "dad", time: "6:40 PM", text: "If you change your mind" },
    { from: "maya", time: "6:42 PM", text: "ok" },

    { day: "Saturday 18 October" },
    { from: "maya", time: "10:05 AM", text: "dad" },
    { from: "dad", time: "10:05 AM", text: "Yes?" },
    { from: "maya", time: "10:06 AM", text: "I need money" },
    { from: "dad", time: "10:06 AM", text: "How much?" },
    { from: "maya", time: "10:07 AM", text: "110" },
    { from: "dad", time: "10:07 AM", text: "Done" },
    { from: "dad", time: "10:07 AM", text: "Sent" },
    { from: "dad", time: "10:08 AM", text: "Maya" },
    { from: "maya", time: "10:10 AM", text: "yes" },
    { from: "dad", time: "10:10 AM", text: "Is something wrong?" },
    { from: "maya", time: "10:11 AM", text: "no" },
    { from: "dad", time: "10:11 AM", text: "You've been asking a lot" },
    { from: "maya", time: "10:12 AM", text: "is that a problem" },
    { from: "dad", time: "10:12 AM", text: "No" },
    { from: "dad", time: "10:12 AM", text: "Never" },
    { from: "dad", time: "10:13 AM", text: "I just want to make sure you're okay" },
    { from: "maya", time: "10:14 AM", text: "I'm fine" },
    { from: "dad", time: "10:14 AM", text: "Okay" },
    { from: "dad", time: "10:15 AM", text: "I love you" },
    { from: "maya", time: "10:17 AM", text: "thanks" },

    { day: "Sunday 26 October" },
    { from: "dad", time: "4:00 PM", text: "Maya" },
    { from: "dad", time: "4:00 PM", text: "I transferred £150" },
    { from: "dad", time: "4:01 PM", text: "For the winter" },
    { from: "dad", time: "4:01 PM", text: "Buy a warm coat" },
    { from: "dad", time: "4:02 PM", text: "Your mum said you don't have one" },
    { from: "maya", time: "4:15 PM", text: "I have a coat" },
    { from: "dad", time: "4:15 PM", text: "A proper one" },
    { from: "maya", time: "4:16 PM", text: "it's fine" },
    { from: "dad", time: "4:16 PM", text: "Buy a warm one" },
    { from: "dad", time: "4:17 PM", text: "Please" },
    { from: "maya", time: "4:20 PM", text: "ok" },
    { from: "dad", time: "4:20 PM", text: "Thank you" },
    { from: "dad", time: "4:21 PM", text: "I love you" },
    { from: "maya", time: "4:25 PM", text: "thanks" },

    { day: "Saturday 1 November" },
    { from: "maya", time: "11:15 AM", text: "dad" },
    { from: "dad", time: "11:15 AM", text: "Yes?" },
    { from: "maya", time: "11:16 AM", text: "I need money" },
    { from: "dad", time: "11:16 AM", text: "How much?" },
    { from: "maya", time: "11:17 AM", text: "55" },
    { from: "dad", time: "11:17 AM", text: "Done" },
    { from: "dad", time: "11:17 AM", text: "Sent" },
    { from: "dad", time: "11:18 AM", text: "Maya" },
    { from: "maya", time: "11:20 AM", text: "yes" },
    { from: "dad", time: "11:20 AM", text: "Can I ask you something?" },
    { from: "maya", time: "11:21 AM", text: "what" },
    { from: "dad", time: "11:21 AM", text: "Are you happy?" },
    { from: "maya", time: "11:22 AM", text: "what" },
    { from: "dad", time: "11:22 AM", text: "Are you happy?" },
    { from: "maya", time: "11:23 AM", text: "what kind of question is that" },
    { from: "dad", time: "11:23 AM", text: "A dad question" },
    { from: "maya", time: "11:25 AM", text: "I don't know" },
    { from: "dad", time: "11:25 AM", text: "That's okay" },
    { from: "dad", time: "11:26 AM", text: "You don't have to know" },
    { from: "maya", time: "11:27 AM", text: "ok" },
    { from: "dad", time: "11:27 AM", text: "I love you" },
    { from: "maya", time: "11:29 AM", text: "thanks" },

    { day: "Saturday 8 November" },
    { from: "maya", time: "1:00 PM", text: "dad" },
    { from: "dad", time: "1:00 PM", text: "Yes?" },
    { from: "maya", time: "1:01 PM", text: "I need money" },
    { from: "dad", time: "1:01 PM", text: "How much?" },
    { from: "maya", time: "1:02 PM", text: "75" },
    { from: "dad", time: "1:02 PM", text: "Done" },
    { from: "dad", time: "1:02 PM", text: "Sent" },
    { from: "dad", time: "1:03 PM", text: "Maya" },
    { from: "maya", time: "1:05 PM", text: "yes" },
    { from: "dad", time: "1:05 PM", text: "Are you eating?" },
    { from: "maya", time: "1:06 PM", text: "yes" },
    { from: "dad", time: "1:06 PM", text: "What did you eat today?" },
    { from: "maya", time: "1:07 PM", text: "food" },
    { from: "dad", time: "1:07 PM", text: "What food?" },
    { from: "maya", time: "1:08 PM", text: "edible food" },
    { from: "dad", time: "1:08 PM", text: "Maya" },
    { from: "maya", time: "1:09 PM", text: "dad" },
    { from: "dad", time: "1:09 PM", text: "I'm just asking" },
    { from: "maya", time: "1:10 PM", text: "you're always just asking" },
    { from: "dad", time: "1:10 PM", text: "Because I care" },
    { from: "maya", time: "1:11 PM", text: "you care from a distance" },
    { from: "dad", time: "1:11 PM", text: "That's not fair" },
    { from: "maya", time: "1:12 PM", text: "it's accurate" },
    { from: "dad", time: "1:12 PM", text: "Same thing" },
    { from: "maya", time: "1:13 PM", text: "it's not" },
    { from: "dad", time: "1:13 PM", text: "I'm trying" },
    { from: "maya", time: "1:14 PM", text: "I know" },
    { from: "dad", time: "1:14 PM", text: "So?" },
    { from: "maya", time: "1:15 PM", text: "so what" },
    { from: "dad", time: "1:15 PM", text: "So give me a chance" },
    { from: "maya", time: "1:16 PM", text: "I've given you chances" },
    { from: "dad", time: "1:16 PM", text: "I know" },
    { from: "dad", time: "1:16 PM", text: "I've wasted them" },
    { from: "dad", time: "1:17 PM", text: "But I'm here now" },
    { from: "maya", time: "1:18 PM", text: "you're always \"here now\"" },
    { from: "maya", time: "1:18 PM", text: "and then you disappear" },
    { from: "dad", time: "1:18 PM", text: "I won't disappear this time" },
    { from: "maya", time: "1:19 PM", text: "you always say that" },
    { from: "dad", time: "1:19 PM", text: "I mean it this time" },
    { from: "maya", time: "1:20 PM", text: "you meant it last time" },
    { from: "dad", time: "1:20 PM", text: "I know" },
    { from: "dad", time: "1:21 PM", text: "But this time is different" },
    { from: "maya", time: "1:22 PM", text: "why" },
    { from: "dad", time: "1:22 PM", text: "Because I'm scared" },
    { from: "maya", time: "1:23 PM", text: "scared of what" },
    { from: "dad", time: "1:23 PM", text: "Scared of losing you" },
    { from: "dad", time: "1:24 PM", text: "For real this time" },
    { from: "maya", time: "1:25 PM", text: "you already lost me" },
    { from: "dad", time: "1:25 PM", text: "I know" },
    { from: "dad", time: "1:26 PM", text: "But I'm trying to find you again" },
    { from: "maya", time: "1:27 PM", text: "🙄" },
    { from: "dad", time: "1:27 PM", text: "There's the eye roll" },
    { from: "dad", time: "1:28 PM", text: "Your mother" },
    { from: "maya", time: "1:28 PM", text: "SHUT UP" },
    { from: "dad", time: "1:29 PM", text: "😂" },
    { from: "maya", time: "1:29 PM", text: "I hate you" },
    { from: "dad", time: "1:30 PM", text: "You love me" },
    { from: "maya", time: "1:30 PM", text: "debatable" },
    { from: "dad", time: "1:31 PM", text: "I'll take debatable" },
    { from: "maya", time: "1:31 PM", text: "🙄" },
    { from: "dad", time: "1:32 PM", text: "Maya?" },
    { from: "maya", time: "1:33 PM", text: "yeah" },
    { from: "dad", time: "1:33 PM", text: "Are you okay?" },
    { from: "maya", time: "1:34 PM", text: "I don't know" },
    { from: "dad", time: "1:34 PM", text: "That's okay" },
    { from: "dad", time: "1:35 PM", text: "You don't have to know" },
    { from: "maya", time: "1:36 PM", text: "thanks" },
    { from: "dad", time: "1:36 PM", text: "For what?" },
    { from: "maya", time: "1:37 PM", text: "for not pushing" },
    { from: "dad", time: "1:37 PM", text: "I'm learning" },
    { from: "maya", time: "1:38 PM", text: "yeah" },
    { from: "maya", time: "1:38 PM", text: "you are" },
    { from: "dad", time: "1:38 PM", text: "I love you" },
    { from: "maya", time: "1:39 PM", text: "I know" },
    { from: "dad", time: "1:40 PM", text: "Do you love me?" },
    { from: "maya", time: "1:42 PM", text: "..." },
    { from: "maya", time: "1:43 PM", text: "maybe" },
    { from: "dad", time: "1:43 PM", text: "I'll take maybe" },
    { from: "maya", time: "1:44 PM", text: "🙄" },
    { from: "dad", time: "1:44 PM", text: "There it is" },
    { from: "maya", time: "1:45 PM", text: "shut up" },
    { from: "dad", time: "1:45 PM", text: "😂" },

    { day: "Sunday 9 November" },
    { from: "maya", time: "7:30 PM", text: "dad" },
    { from: "dad", time: "7:30 PM", text: "Yes?" },
    { from: "maya", time: "7:31 PM", text: "are you still at work" },
    { from: "dad", time: "7:31 PM", text: "No, why?" },
    { from: "maya", time: "7:32 PM", text: "just asking" },
    { from: "dad", time: "7:32 PM", text: "You never just ask" },
    { from: "maya", time: "7:33 PM", text: "I do now" },
    { from: "dad", time: "7:33 PM", text: "Since when?" },
    { from: "maya", time: "7:34 PM", text: "since today" },
    { from: "dad", time: "7:34 PM", text: "Okay" },
    { from: "dad", time: "7:35 PM", text: "I'm not at work" },
    { from: "dad", time: "7:35 PM", text: "I'm home" },
    { from: "maya", time: "7:36 PM", text: "cool" },
    { from: "dad", time: "7:36 PM", text: "Cool" },
    { from: "dad", time: "7:37 PM", text: "Are you okay?" },
    { from: "maya", time: "7:38 PM", text: "yeah" },
    { from: "maya", time: "7:39 PM", text: "are you?" },
    { from: "dad", time: "7:39 PM", text: "..." },
    { from: "dad", time: "7:40 PM", text: "I'm okay" },
    { from: "dad", time: "7:40 PM", text: "Why are you asking?" },
    { from: "maya", time: "7:41 PM", text: "no reason" },
    { from: "dad", time: "7:41 PM", text: "Maya" },
    { from: "maya", time: "7:42 PM", text: "dad" },
    { from: "dad", time: "7:42 PM", text: "You're being weird" },
    { from: "maya", time: "7:43 PM", text: "I'm being nice" },
    { from: "dad", time: "7:43 PM", text: "Same thing" },
    { from: "maya", time: "7:44 PM", text: "it's not" },
    { from: "dad", time: "7:44 PM", text: "It is for you" },
    { from: "maya", time: "7:45 PM", text: "😐" },
    { from: "dad", time: "7:45 PM", text: "😂" },
    { from: "dad", time: "7:46 PM", text: "There she is" },
    { from: "maya", time: "7:46 PM", text: "whatever" },
    { from: "dad", time: "7:47 PM", text: "I love you" },
    { from: "maya", time: "7:48 PM", text: "yeah" },
    { from: "dad", time: "7:48 PM", text: "Say it back" },
    { from: "maya", time: "7:49 PM", text: "no" },
    { from: "dad", time: "7:49 PM", text: "Say it" },
    { from: "maya", time: "7:50 PM", text: "NO" },
    { from: "dad", time: "7:50 PM", text: "SAY IT" },
    { from: "maya", time: "7:51 PM", text: "fine" },
    { from: "maya", time: "7:51 PM", text: "I love you too" },
    { from: "dad", time: "7:52 PM", text: "..." },
    { from: "dad", time: "7:52 PM", text: "You've never said that before" },
    { from: "maya", time: "7:53 PM", text: "don't make it weird" },
    { from: "dad", time: "7:53 PM", text: "Too late" },
    { from: "dad", time: "7:54 PM", text: "I'm crying" },
    { from: "maya", time: "7:54 PM", text: "you're not" },
    { from: "dad", time: "7:55 PM", text: "I'm not" },
    { from: "dad", time: "7:55 PM", text: "But I'm smiling" },
    { from: "maya", time: "7:56 PM", text: "good" },
    { from: "dad", time: "7:56 PM", text: "Thank you Maya" },
    { from: "maya", time: "7:57 PM", text: "for what" },
    { from: "dad", time: "7:57 PM", text: "For saying it" },
    { from: "maya", time: "7:58 PM", text: "don't get used to it" },
    { from: "dad", time: "7:58 PM", text: "I won't" },
    { from: "dad", time: "7:59 PM", text: "But I'll remember it" },
    { from: "maya", time: "8:00 PM", text: "🙄" },
    { from: "dad", time: "8:01 PM", text: "Goodnight Maya" },
    { from: "maya", time: "8:02 PM", text: "goodnight dad" },

    { day: "Saturday 15 November" },
    { from: "maya", time: "10:45 AM", text: "dad" },
    { from: "dad", time: "10:45 AM", text: "Yes?" },
    { from: "maya", time: "10:46 AM", text: "I need money" },
    { from: "dad", time: "10:46 AM", text: "How much?" },
    { from: "maya", time: "10:47 AM", text: "40" },
    { from: "dad", time: "10:47 AM", text: "Done" },
    { from: "dad", time: "10:47 AM", text: "Sent" },
    { from: "dad", time: "10:48 AM", text: "Maya" },
    { from: "maya", time: "10:50 AM", text: "yes" },
    { from: "dad", time: "10:50 AM", text: "I'm coming to Ashcombe next weekend" },
    { from: "dad", time: "10:50 AM", text: "Can I see you?" },
    { from: "maya", time: "10:52 AM", text: "..." },
    { from: "dad", time: "10:53 AM", text: "Maya?" },
    { from: "maya", time: "10:54 AM", text: "maybe" },
    { from: "dad", time: "10:54 AM", text: "Maybe?" },
    { from: "maya", time: "10:55 AM", text: "maybe yes" },
    { from: "dad", time: "10:55 AM", text: "Really?" },
    { from: "maya", time: "10:56 AM", text: "don't get excited" },
    { from: "dad", time: "10:56 AM", text: "Too late" },
    { from: "dad", time: "10:57 AM", text: "I'm excited" },
    { from: "maya", time: "10:57 AM", text: "dad" },
    { from: "dad", time: "10:57 AM", text: "What?" },
    { from: "maya", time: "10:58 AM", text: "calm down" },
    { from: "dad", time: "10:58 AM", text: "I can't" },
    { from: "dad", time: "10:59 AM", text: "I'm seeing my daughter" },
    { from: "maya", time: "10:59 AM", text: "🙄" },
    { from: "dad", time: "11:00 AM", text: "Saturday" },
    { from: "dad", time: "11:00 AM", text: "11am" },
    { from: "dad", time: "11:00 AM", text: "The park with the pond" },
    { from: "maya", time: "11:01 AM", text: "I know" },
    { from: "dad", time: "11:01 AM", text: "I'll bring sandwiches" },
    { from: "maya", time: "11:02 AM", text: "cheese and pickle?" },
    { from: "dad", time: "11:02 AM", text: "You remember?" },
    { from: "maya", time: "11:03 AM", text: "unfortunately" },
    { from: "dad", time: "11:03 AM", text: "I'm bringing them" },
    { from: "dad", time: "11:04 AM", text: "And hot chocolate" },
    { from: "maya", time: "11:04 AM", text: "it's not cold" },
    { from: "dad", time: "11:04 AM", text: "It's November" },
    { from: "maya", time: "11:05 AM", text: "it's fine" },
    { from: "dad", time: "11:05 AM", text: "It's not" },
    { from: "dad", time: "11:06 AM", text: "I'm bringing hot chocolate" },
    { from: "maya", time: "11:06 AM", text: "FINE" },
    { from: "dad", time: "11:07 AM", text: "😂" },
    { from: "dad", time: "11:07 AM", text: "I love you" },
    { from: "maya", time: "11:08 AM", text: "yeah yeah" },
    { from: "dad", time: "11:08 AM", text: "SAY IT" },
    { from: "maya", time: "11:09 AM", text: "I love you too" },
    { from: "dad", time: "11:09 AM", text: "I'll never get tired of that" },
    { from: "maya", time: "11:10 AM", text: "don't push it" },
    { from: "dad", time: "11:10 AM", text: "Noted" },
    { from: "dad", time: "11:11 AM", text: "See you Saturday" },
    { from: "maya", time: "11:12 AM", text: "see you" },

    { day: "Tuesday 18 November" },
    { from: "dad", time: "8:00 PM", text: "Maya" },
    { from: "dad", time: "8:00 PM", text: "What kind of sandwiches do you want?" },
    { from: "dad", time: "8:01 PM", text: "Cheese and pickle like usual?" },
    { from: "dad", time: "8:01 PM", text: "Or something else?" },
    { from: "dad", time: "8:02 PM", text: "I can do ham" },
    { from: "dad", time: "8:02 PM", text: "Or chicken" },
    { from: "dad", time: "8:03 PM", text: "Or egg" },
    { from: "dad", time: "8:05 PM", text: "Maya" },
    { from: "maya", time: "8:15 PM", text: "dad" },
    { from: "dad", time: "8:15 PM", text: "Yes?" },
    { from: "maya", time: "8:16 PM", text: "you're sending a lot of messages" },
    { from: "dad", time: "8:16 PM", text: "Sorry" },
    { from: "dad", time: "8:17 PM", text: "I'm nervous" },
    { from: "maya", time: "8:18 PM", text: "why" },
    { from: "dad", time: "8:18 PM", text: "Because I haven't seen you properly in years" },
    { from: "dad", time: "8:19 PM", text: "I want it to be good" },
    { from: "maya", time: "8:20 PM", text: "it will be" },
    { from: "dad", time: "8:20 PM", text: "You think so?" },
    { from: "maya", time: "8:21 PM", text: "yeah" },
    { from: "dad", time: "8:21 PM", text: "Okay" },
    { from: "dad", time: "8:22 PM", text: "Cheese and pickle it is" },
    { from: "maya", time: "8:23 PM", text: "good" },
    { from: "dad", time: "8:24 PM", text: "Should I bring the chess set?" },
    { from: "maya", time: "8:25 PM", text: "what" },
    { from: "dad", time: "8:25 PM", text: "Remember we used to play?" },
    { from: "maya", time: "8:26 PM", text: "I was 8" },
    { from: "dad", time: "8:26 PM", text: "You were good" },
    { from: "maya", time: "8:27 PM", text: "I was terrible" },
    { from: "dad", time: "8:27 PM", text: "You were 8" },
    { from: "maya", time: "8:28 PM", text: "fair" },
    { from: "dad", time: "8:28 PM", text: "So chess?" },
    { from: "maya", time: "8:29 PM", text: "no" },
    { from: "dad", time: "8:29 PM", text: "Okay" },
    { from: "dad", time: "8:30 PM", text: "Just sandwiches then" },
    { from: "maya", time: "8:31 PM", text: "and hot chocolate" },
    { from: "dad", time: "8:31 PM", text: "You want the hot chocolate?" },
    { from: "maya", time: "8:32 PM", text: "you're bringing it anyway" },
    { from: "dad", time: "8:32 PM", text: "Yes" },
    { from: "maya", time: "8:33 PM", text: "then yes" },
    { from: "dad", time: "8:33 PM", text: "😂" },
    { from: "dad", time: "8:34 PM", text: "Okay" },
    { from: "dad", time: "8:34 PM", text: "See you Saturday" },
    { from: "maya", time: "8:35 PM", text: "see you" },

    { day: "Thursday 20 November" },
    { from: "maya", time: "9:15 PM", text: "dad" },
    { from: "dad", time: "9:15 PM", text: "Yes?" },
    { from: "maya", time: "9:16 PM", text: "what was my mum like when you met her" },
    { from: "dad", time: "9:17 PM", text: "..." },
    { from: "dad", time: "9:18 PM", text: "Why are you asking?" },
    { from: "maya", time: "9:19 PM", text: "just curious" },
    { from: "dad", time: "9:20 PM", text: "She was beautiful" },
    { from: "dad", time: "9:20 PM", text: "She laughed a lot" },
    { from: "dad", time: "9:21 PM", text: "She was kind" },
    { from: "dad", time: "9:21 PM", text: "She made me feel like I mattered" },
    { from: "maya", time: "9:22 PM", text: "what happened" },
    { from: "dad", time: "9:23 PM", text: "I don't know" },
    { from: "dad", time: "9:23 PM", text: "We were young" },
    { from: "dad", time: "9:24 PM", text: "We made mistakes" },
    { from: "maya", time: "9:25 PM", text: "that's not an answer" },
    { from: "dad", time: "9:25 PM", text: "It's the only one I have" },
    { from: "maya", time: "9:26 PM", text: "okay" },
    { from: "dad", time: "9:27 PM", text: "Maya" },
    { from: "maya", time: "9:28 PM", text: "yeah" },
    { from: "dad", time: "9:28 PM", text: "Is everything okay?" },
    { from: "maya", time: "9:29 PM", text: "I don't know" },
    { from: "dad", time: "9:29 PM", text: "Talk to me" },
    { from: "maya", time: "9:30 PM", text: "I can't" },
    { from: "dad", time: "9:30 PM", text: "Why not?" },
    { from: "maya", time: "9:31 PM", text: "because" },
    { from: "dad", time: "9:31 PM", text: "Because why?" },
    { from: "maya", time: "9:32 PM", text: "because I don't know how" },
    { from: "dad", time: "9:32 PM", text: "Just say it" },
    { from: "dad", time: "9:33 PM", text: "Whatever it is" },
    { from: "dad", time: "9:33 PM", text: "I won't judge" },
    { from: "maya", time: "9:34 PM", text: "I'm scared" },
    { from: "dad", time: "9:34 PM", text: "Scared of what?" },
    { from: "maya", time: "9:35 PM", text: "everything" },
    { from: "dad", time: "9:35 PM", text: "..." },
    { from: "dad", time: "9:36 PM", text: "Maya" },
    { from: "maya", time: "9:37 PM", text: "I have to go" },
    { from: "dad", time: "9:37 PM", text: "Wait" },
    { from: "dad", time: "9:37 PM", text: "Maya" },
    { from: "dad", time: "9:38 PM", text: "Maya" },
    { from: "dad", time: "9:38 PM", text: "Please" },
    { from: "dad", time: "9:39 PM", text: "I'm here" },
    { from: "dad", time: "9:39 PM", text: "Whatever it is" },
    { from: "dad", time: "9:40 PM", text: "I'm here" },
    { from: "maya", time: "9:55 PM", text: "I know" },
    { from: "maya", time: "9:55 PM", text: "thanks dad" },
    { from: "dad", time: "9:55 PM", text: "You don't have to thank me" },
    { from: "maya", time: "9:56 PM", text: "I want to" },
    { from: "dad", time: "9:57 PM", text: "..." },
    { from: "dad", time: "9:57 PM", text: "I love you" },
    { from: "maya", time: "9:58 PM", text: "I love you too" },
    { from: "dad", time: "9:58 PM", text: "Maya" },
    { from: "maya", time: "9:59 PM", text: "yeah" },
    { from: "dad", time: "9:59 PM", text: "Are you safe?" },
    { from: "maya", time: "10:00 PM", text: "..." },
    { from: "maya", time: "10:01 PM", text: "I don't know" },
    { from: "dad", time: "10:01 PM", text: "What does that mean?" },
    { from: "maya", time: "10:02 PM", text: "I have to go" },
    { from: "dad", time: "10:02 PM", text: "Maya" },
    { from: "dad", time: "10:03 PM", text: "MAYA" },
    { from: "dad", time: "10:03 PM", text: "Please" },

    { day: "Thursday 20 November, later" },
    { from: "maya", time: "11:30 PM", text: "sorry" },
    { from: "dad", time: "11:30 PM", text: "Oh thank god" },
    { from: "dad", time: "11:30 PM", text: "Maya" },
    { from: "dad", time: "11:31 PM", text: "What's going on?" },
    { from: "maya", time: "11:32 PM", text: "I can't explain" },
    { from: "dad", time: "11:32 PM", text: "Try" },
    { from: "maya", time: "11:33 PM", text: "I can't" },
    { from: "dad", time: "11:33 PM", text: "Maya" },
    { from: "maya", time: "11:34 PM", text: "dad please" },
    { from: "maya", time: "11:34 PM", text: "just trust me" },
    { from: "dad", time: "11:34 PM", text: "I always trust you" },
    { from: "maya", time: "11:35 PM", text: "then let it go" },
    { from: "dad", time: "11:35 PM", text: "..." },
    { from: "dad", time: "11:36 PM", text: "Okay" },
    { from: "dad", time: "11:36 PM", text: "I'll let it go" },
    { from: "dad", time: "11:37 PM", text: "But if you need me" },
    { from: "dad", time: "11:37 PM", text: "I'm here" },
    { from: "maya", time: "11:38 PM", text: "I know" },
    { from: "dad", time: "11:38 PM", text: "Promise me you'll ask" },
    { from: "maya", time: "11:39 PM", text: "I promise" },
    { from: "dad", time: "11:39 PM", text: "Okay" },
    { from: "dad", time: "11:40 PM", text: "I love you" },
    { from: "maya", time: "11:41 PM", text: "I love you too" },
    { from: "dad", time: "11:41 PM", text: "See you Saturday" },
    { from: "maya", time: "11:42 PM", text: "see you Saturday" },

    { day: "Friday 21 November" },
    { from: "maya", time: "7:45 PM", text: "dad" },
    { from: "dad", time: "7:45 PM", text: "Yes?" },
    { from: "maya", time: "7:46 PM", text: "what was your favourite thing about being my dad" },
    { from: "dad", time: "7:47 PM", text: "..." },
    { from: "dad", time: "7:47 PM", text: "Maya" },
    { from: "maya", time: "7:48 PM", text: "just answer" },
    { from: "dad", time: "7:49 PM", text: "Your laugh" },
    { from: "dad", time: "7:49 PM", text: "When you were little" },
    { from: "dad", time: "7:50 PM", text: "You used to laugh at everything" },
    { from: "dad", time: "7:50 PM", text: "Even my bad jokes" },
    { from: "maya", time: "7:51 PM", text: "they were bad" },
    { from: "dad", time: "7:51 PM", text: "They were" },
    { from: "dad", time: "7:52 PM", text: "But you laughed" },
    { from: "maya", time: "7:52 PM", text: "I was a baby" },
    { from: "dad", time: "7:53 PM", text: "You were 5" },
    { from: "maya", time: "7:53 PM", text: "same thing" },
    { from: "dad", time: "7:53 PM", text: "It's not" },
    { from: "maya", time: "7:54 PM", text: "it is" },
    { from: "dad", time: "7:54 PM", text: "😂" },
    { from: "dad", time: "7:55 PM", text: "I love you" },
    { from: "maya", time: "7:55 PM", text: "I love you too" },
    { from: "dad", time: "7:56 PM", text: "Maya" },
    { from: "maya", time: "7:57 PM", text: "yeah" },
    { from: "dad", time: "7:57 PM", text: "Are you okay?" },
    { from: "maya", time: "7:58 PM", text: "I'm fine" },
    { from: "dad", time: "7:58 PM", text: "You keep saying that" },
    { from: "maya", time: "7:59 PM", text: "because it's true" },
    { from: "dad", time: "7:59 PM", text: "It's not" },
    { from: "maya", time: "8:00 PM", text: "dad" },
    { from: "dad", time: "8:00 PM", text: "I know" },
    { from: "dad", time: "8:00 PM", text: "I'll stop" },
    { from: "maya", time: "8:01 PM", text: "thanks" },
    { from: "dad", time: "8:01 PM", text: "I love you" },
    { from: "maya", time: "8:02 PM", text: "you said that" },
    { from: "dad", time: "8:02 PM", text: "I'll keep saying it" },
    { from: "maya", time: "8:03 PM", text: "🙄" },
    { from: "dad", time: "8:03 PM", text: "There it is" },
    { from: "maya", time: "8:04 PM", text: "shut up" },
    { from: "dad", time: "8:04 PM", text: "Never" },

    { day: "Saturday 22 November" },
    { from: "dad", time: "10:45 AM", text: "I'm at the park" },
    { from: "dad", time: "10:45 AM", text: "Benches by the pond" },
    { from: "dad", time: "10:45 AM", text: "I brought sandwiches" },
    { from: "dad", time: "10:46 AM", text: "Cheese and pickle" },
    { from: "dad", time: "10:46 AM", text: "And hot chocolate" },
    { from: "dad", time: "10:46 AM", text: "Extra marshmallows" },
    { from: "dad", time: "11:00 AM", text: "Maya?" },
    { from: "dad", time: "11:15 AM", text: "It's 11:15" },
    { from: "dad", time: "11:15 AM", text: "I'm here" },
    { from: "dad", time: "11:16 AM", text: "Take your time" },
    { from: "dad", time: "11:16 AM", text: "I'll wait" },
    { from: "maya", time: "11:18 AM", text: "I'm coming" },
    { from: "dad", time: "11:18 AM", text: "Really?" },
    { from: "maya", time: "11:19 AM", text: "yes" },
    { from: "dad", time: "11:19 AM", text: "I'm so happy" },
    { from: "maya", time: "11:20 AM", text: "don't cry" },
    { from: "dad", time: "11:20 AM", text: "I'm not crying" },
    { from: "dad", time: "11:20 AM", text: "I'm just" },
    { from: "dad", time: "11:21 AM", text: "Happy" },
    { from: "maya", time: "11:22 AM", text: "dad" },
    { from: "dad", time: "11:22 AM", text: "Yes?" },
    { from: "maya", time: "11:23 AM", text: "I'll be there in 15 minutes" },
    { from: "dad", time: "11:23 AM", text: "I'll be here" },
    { from: "dad", time: "11:24 AM", text: "I'll always be here" },
    { from: "maya", time: "11:25 AM", text: "I know" },
    { from: "maya", time: "11:25 AM", text: "see you soon" },
    { from: "dad", time: "11:25 AM", text: "See you soon" },

    { day: "Sunday 23 November" },
    { from: "maya", time: "9:15 AM", text: "dad" },
    { from: "dad", time: "9:15 AM", text: "Maya" },
    { from: "dad", time: "9:16 AM", text: "Yesterday was" },
    { from: "dad", time: "9:16 AM", text: "I don't have words" },
    { from: "maya", time: "9:18 AM", text: "me neither" },
    { from: "dad", time: "9:18 AM", text: "Thank you" },
    { from: "maya", time: "9:19 AM", text: "for what" },
    { from: "dad", time: "9:19 AM", text: "For coming" },
    { from: "dad", time: "9:20 AM", text: "For giving me a chance" },
    { from: "maya", time: "9:22 AM", text: "you earned it" },
    { from: "dad", time: "9:22 AM", text: "Did I?" },
    { from: "maya", time: "9:23 AM", text: "yeah" },
    { from: "maya", time: "9:23 AM", text: "you did" },
    { from: "dad", time: "9:23 AM", text: "I'll keep earning it" },
    { from: "maya", time: "9:25 AM", text: "I know" },
    { from: "dad", time: "9:26 AM", text: "Same time next weekend?" },
    { from: "maya", time: "9:28 AM", text: "..." },
    { from: "maya", time: "9:30 AM", text: "yeah" },
    { from: "dad", time: "9:30 AM", text: "Really?" },
    { from: "maya", time: "9:31 AM", text: "don't push it" },
    { from: "dad", time: "9:31 AM", text: "Sorry" },
    { from: "dad", time: "9:31 AM", text: "Yes" },
    { from: "dad", time: "9:32 AM", text: "Same time next weekend" },
    { from: "maya", time: "9:33 AM", text: "okay" },
    { from: "dad", time: "9:33 AM", text: "I love you" },
    { from: "maya", time: "9:34 AM", text: "I love you too" },
    { from: "dad", time: "9:34 AM", text: "I'm going to cry" },
    { from: "maya", time: "9:35 AM", text: "don't" },
    { from: "dad", time: "9:35 AM", text: "Too late" },
    { from: "maya", time: "9:36 AM", text: "DAD" },
    { from: "dad", time: "9:36 AM", text: "😂" },
    { from: "dad", time: "9:37 AM", text: "Goodnight Maya" },
    { from: "maya", time: "9:38 AM", text: "goodnight dad" },
    { from: "maya", time: "9:40 AM", text: "hey" },
    { from: "dad", time: "9:40 AM", text: "Yes?" },
    { from: "maya", time: "9:41 AM", text: "thanks" },
    { from: "dad", time: "9:41 AM", text: "For what?" },
    { from: "maya", time: "9:42 AM", text: "for being my dad" },
    { from: "dad", time: "9:43 AM", text: "..." },
    { from: "dad", time: "9:43 AM", text: "I'm going to cry for real now" },
    { from: "maya", time: "9:44 AM", text: "😐" },
    { from: "dad", time: "9:44 AM", text: "I love you" },
    { from: "maya", time: "9:45 AM", text: "I love you too" },
    { from: "dad", time: "9:45 AM", text: "Goodnight" },
    { from: "maya", time: "9:46 AM", text: "goodnight" },

    { day: "Monday 24 November" },
    { from: "dad", time: "8:00 PM", text: "Maya" },
    { from: "dad", time: "8:00 PM", text: "I've been thinking" },
    { from: "dad", time: "8:01 PM", text: "About yesterday" },
    { from: "dad", time: "8:01 PM", text: "About everything" },
    { from: "dad", time: "8:02 PM", text: "I know I've been a terrible dad" },
    { from: "dad", time: "8:02 PM", text: "I know I've missed everything" },
    { from: "dad", time: "8:03 PM", text: "Birthdays" },
    { from: "dad", time: "8:03 PM", text: "School stuff" },
    { from: "dad", time: "8:03 PM", text: "Everything" },
    { from: "dad", time: "8:04 PM", text: "But yesterday was the best day I've had in years" },
    { from: "dad", time: "8:04 PM", text: "And I want more days like that" },
    { from: "dad", time: "8:05 PM", text: "I want to be your dad" },
    { from: "dad", time: "8:05 PM", text: "For real this time" },
    { from: "dad", time: "8:06 PM", text: "Not just money" },
    { from: "dad", time: "8:06 PM", text: "Not just texts" },
    { from: "dad", time: "8:07 PM", text: "I want to show up" },
    { from: "dad", time: "8:07 PM", text: "Every time" },
    { from: "dad", time: "8:08 PM", text: "I know you're angry" },
    { from: "dad", time: "8:08 PM", text: "You have every right to be" },
    { from: "dad", time: "8:09 PM", text: "But I'm not giving up" },
    { from: "dad", time: "8:09 PM", text: "I'll never give up" },
    { from: "dad", time: "8:10 PM", text: "I'll pick you up Saturday" },
    { from: "dad", time: "8:10 PM", text: "10am" },
    { from: "dad", time: "8:11 PM", text: "Don't argue" },
    { from: "dad", time: "8:11 PM", text: "We'll go to the park" },
    { from: "dad", time: "8:12 PM", text: "The one with the pond" },
    { from: "dad", time: "8:12 PM", text: "Remember?" },
    { from: "dad", time: "8:13 PM", text: "We used to feed the ducks" },
    { from: "dad", time: "8:13 PM", text: "You were 5" },
    { from: "dad", time: "8:14 PM", text: "You called them \"quack quacks\"" },
    { from: "dad", time: "8:14 PM", text: "I still think about that" },
    { from: "dad", time: "8:15 PM", text: "I still think about you" },
    { from: "dad", time: "8:15 PM", text: "Every day" },
    { from: "dad", time: "8:16 PM", text: "I know you don't believe me" },
    { from: "dad", time: "8:16 PM", text: "But I do" },
    { from: "dad", time: "8:17 PM", text: "I'll be there Saturday" },
    { from: "dad", time: "8:17 PM", text: "10am" },
    { from: "dad", time: "8:18 PM", text: "I'll wait all day if I have to" },
    { from: "dad", time: "8:18 PM", text: "I love you Maya" },
    { from: "dad", time: "8:19 PM", text: "Always" },
    { from: "maya", time: "9:00 PM", text: "dad" },
    { from: "dad", time: "9:00 PM", text: "Maya?" },
    { from: "maya", time: "9:01 PM", text: "I'll be there" },
    { from: "dad", time: "9:01 PM", text: "You will?" },
    { from: "maya", time: "9:02 PM", text: "yeah" },
    { from: "maya", time: "9:02 PM", text: "I promise" },
    { from: "dad", time: "9:03 PM", text: "I'm going to cry" },
    { from: "maya", time: "9:03 PM", text: "don't" },
    { from: "dad", time: "9:03 PM", text: "Too late" },
    { from: "maya", time: "9:04 PM", text: "😂" },
    { from: "dad", time: "9:04 PM", text: "I love you" },
    { from: "maya", time: "9:05 PM", text: "I love you too" },
    { from: "dad", time: "9:05 PM", text: "See you Saturday" },
    { from: "maya", time: "9:06 PM", text: "see you Saturday" },
    { from: "dad", time: "9:07 PM", text: "Goodnight Maya" },
    { from: "maya", time: "9:08 PM", text: "goodnight dad" },
    { from: "maya", time: "9:10 PM", text: "hey dad" },
    { from: "dad", time: "9:10 PM", text: "Yes?" },
    { from: "maya", time: "9:11 PM", text: "I'm glad you're my dad" },
    { from: "dad", time: "9:12 PM", text: "..." },
    { from: "dad", time: "9:12 PM", text: "Maya" },
    { from: "dad", time: "9:13 PM", text: "I don't know what to say" },
    { from: "maya", time: "9:14 PM", text: "you don't have to say anything" },
    { from: "dad", time: "9:15 PM", text: "I love you" },
    { from: "maya", time: "9:16 PM", text: "I love you too" },
    { from: "dad", time: "9:17 PM", text: "Goodnight" },
    { from: "maya", time: "9:18 PM", text: "goodnight" }
  ]
};
